// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package getPowerDevicePointNames

import "reflect"

var Types = map[string]reflect.Type{
	"Request": reflect.TypeOf((*Request)(nil)).Elem(),
	"Resource": reflect.TypeOf((*Resource)(nil)).Elem(),
	"Response": reflect.TypeOf((*Response)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

