// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package image

import "reflect"

var Types = map[string]reflect.Type{
	"Count": reflect.TypeOf((*Count)(nil)).Elem(),
	"CountRequest": reflect.TypeOf((*CountRequest)(nil)).Elem(),
	"CountResponse": reflect.TypeOf((*CountResponse)(nil)).Elem(),
	"Create": reflect.TypeOf((*Create)(nil)).Elem(),
	"CreateRequest": reflect.TypeOf((*CreateRequest)(nil)).Elem(),
	"CreateResponse": reflect.TypeOf((*CreateResponse)(nil)).Elem(),
	"Delete": reflect.TypeOf((*Delete)(nil)).Elem(),
	"DeleteRequest": reflect.TypeOf((*DeleteRequest)(nil)).Elem(),
	"DeleteResponse": reflect.TypeOf((*DeleteResponse)(nil)).Elem(),
	"Image": reflect.TypeOf((*Image)(nil)).Elem(),
	"List": reflect.TypeOf((*List)(nil)).Elem(),
	"ListRequest": reflect.TypeOf((*ListRequest)(nil)).Elem(),
	"ListResponse": reflect.TypeOf((*ListResponse)(nil)).Elem(),
	"ListResponseSingle": reflect.TypeOf((*ListResponseSingle)(nil)).Elem(),
	"Read": reflect.TypeOf((*Read)(nil)).Elem(),
	"ReadRequest": reflect.TypeOf((*ReadRequest)(nil)).Elem(),
	"ReadResponse": reflect.TypeOf((*ReadResponse)(nil)).Elem(),
	"ReadResponseSingle": reflect.TypeOf((*ReadResponseSingle)(nil)).Elem(),
	"Update": reflect.TypeOf((*Update)(nil)).Elem(),
	"UpdateRequest": reflect.TypeOf((*UpdateRequest)(nil)).Elem(),
	"UpdateResponse": reflect.TypeOf((*UpdateResponse)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

