./add.sh AppService psHourPointsValue /v1/powerStationService/psHourPointsValue
./add.sh AppService getPsCurveInfo /v1/devService/getPsCurveInfo
./add.sh AppService getTemplateList /v1/devService/getTemplateList
./add.sh AppService getDevicePoints /v1/devService/getDevicePoints
./add.sh AppService getAllPowerDeviceSetName /v1/devService/getAllPowerDeviceSetName
./add.sh AppService queryAllPsIdAndName /v1/powerStationService/queryAllPsIdAndName
./add.sh AppService queryDevicePointMinuteDataList /v1/commonService/queryDevicePointMinuteDataList
./add.sh AppService getTemplateByInfoType /v1/messageService/getTemplateByInfoType
./add.sh AppService energyTrend /v1/powerStationService/energyTrend
./add.sh AppService queryBatchCreatePsTaskList /v1/powerStationService/queryBatchCreatePsTaskList
./add.sh AppService exportPlantReportPDF /v1/powerStationService/exportPlantReportPDF
./add.sh AppService getTableDataSql /v1/devService/getTableDataSql
./add.sh AppService getTableDataSqlCount /v1/devService/getTableDataSqlCount
./add.sh AppService getPListinfoFromMysql /v1/powerStationService/getPListinfoFromMysql
./add.sh AppService getDataFromHBase /v1/commonService/getDataFromHBase
./add.sh AppService getListMiFromHBase /v1/commonService/getListMiFromHBase
./add.sh AppService getMapMiFromHBase /v1/commonService/getMapMiFromHBase
./add.sh AppService getValFromHBase /v1/commonService/getValFromHBase
./add.sh AppService getPowerStationTableDataSql /v1/devService/getPowerStationTableDataSql
./add.sh AppService getPowerStationTableDataSqlCount /v1/devService/getPowerStationTableDataSqlCount
./add.sh AppService getDataFromHbaseByRowKey /v1/commonService/getDataFromHbaseByRowKey
./add.sh AppService findInfoByuuid /v1/devService/findInfoByuuid
./add.sh AppService getStationInfoSql /v1/devService/getStationInfoSql
./add.sh AppService getDevicePointMinuteDataList /v1/commonService/getDevicePointMinuteDataList
./add.sh AppService powerDevicePointList /v1/reportService/powerDevicePointList
./add.sh AppService getPowerTrendDayData /v1/powerStationService/getPowerTrendDayData
./add.sh AppService powerTrendChartData /v1/powerStationService/powerTrendChartData
./add.sh AppService getUpTimePoint /v1/devService/getUpTimePoint
./add.sh AppService getSerialNum /v1/devService/getSerialNum
./add.sh AppService getModuleLogTaskList /integrationService/getModuleLogTaskList
./add.sh AppService queryParamSettingTask /v1/devService/queryParamSettingTask
./add.sh AppService queryCtrlTaskById /v1/devService/queryCtrlTaskById
./add.sh AppService queryDeviceInfo /v1/devService/queryDeviceInfoForApp
./add.sh AppService queryDeviceInfoForApp /v1/devService/queryDeviceInfoForApp
./add.sh AppService queryDeviceList /v1/devService/queryDeviceList
./add.sh AppService queryDeviceListByUserId /v1/devService/queryDeviceListByUserId
./add.sh AppService queryDeviceListForApp /v1/devService/queryDeviceListForApp
./add.sh AppService queryDeviceModelTechnical /v1/devService/queryDeviceModelTechnical
./add.sh AppService getPsDataSupplementTaskList /v1/powerStationService/getPsDataSupplementTaskList
./add.sh AppService getPsDetail /v1/powerStationService/getPsDetail
./add.sh AppService getPsHealthState /v1/powerStationService/getPsHealthState
./add.sh AppService getPowerDeviceSetTaskDetailList /v1/devService/getPowerDeviceSetTaskDetailList
./add.sh AppService getPowerDeviceSetTaskList /v1/devService/getPowerDeviceSetTaskList
./add.sh AppService getPsAuthKey /v1/powerStationService/getPsAuthKey
./add.sh AppService getApiCallsForAppkeys /v1/commonService/getApiCallsForAppkeys
./add.sh AppService exportParamSettingValPDF /v1/devService/exportParamSettingValPDF
./add.sh AppService checkUnitStatus /v1/devService/checkUnitStatus
./add.sh AppService devicePointsDataFromMySql /v1/devService/devicePointsDataFromMySql
./add.sh AppService queryDevicePointDayMonthYearDataList /v1/commonService/queryDevicePointDayMonthYearDataList
./add.sh AppService queryDevicePointsDayMonthYearDataList /v1/commonService/queryDevicePointsDayMonthYearDataList
./add.sh AppService queryDeviceRealTimeDataByPsKeys /v1/devService/queryDeviceRealTimeDataByPsKeys
./add.sh AppService acceptPsSharing /v1/powerStationService/acceptPsSharing
./add.sh AppService activateEmail /v1/userService/activateEmail
./add.sh AppService addConfig /devDataHandleService/addConfig
./add.sh AppService addDeviceRepair /v1/devService/addDeviceRepair
./add.sh AppService addDeviceToStructureForHousehold /devDataHandleService/addDeviceToStructureForHousehold
./add.sh AppService addDeviceToStructureForHouseholdByPsIdS /devDataHandleService/addDeviceToStructureForHouseholdByPsIdS
./add.sh AppService addFault /v1/faultService/addFault
./add.sh AppService addFaultOrder /v1/faultService/addFaultOrder
./add.sh AppService addFaultPlan /v1/faultService/addFaultPlan
./add.sh AppService addFaultRepairSteps /v1/faultService/addFaultRepairSteps
./add.sh AppService addHouseholdEvaluation /v1/faultService/addHouseholdEvaluation
./add.sh AppService addHouseholdLeaveMessage /v1/faultService/addHouseholdLeaveMessage
./add.sh AppService addHouseholdOpinionFeedback /v1/faultService/addHouseholdOpinionFeedback
./add.sh AppService addHouseholdWorkOrder /v1/faultService/addHouseholdWorkOrder
./add.sh AppService addOnDutyInfo /v1/otherService/addOnDutyInfo
./add.sh AppService addOperRule /v1/faultService/addOperRule
./add.sh AppService addOrDelPsStructure /v1/devService/addOrDelPsStructure
./add.sh AppService addOrderStep /v1/faultService/addOrderStep
./add.sh AppService addPowerStationForHousehold /v1/powerStationService/addPowerStationForHousehold
./add.sh AppService addPowerStationInfo /v1/powerStationService/addPowerStationInfo
./add.sh AppService addReportConfigEmail /v1/reportService/addReportConfigEmail
./add.sh AppService addSysAdvancedParam /v1/devService/addSysAdvancedParam
./add.sh AppService addSysOrgNew /v1/otherService/addSysOrgNew
./add.sh AppService aliPayAppTest /onlinepay/aliPayAppTest
./add.sh AppService auditOperRule /v1/faultService/auditOperRule
./add.sh AppService batchAddStationBySn /v1/powerStationService/batchAddStationBySn
./add.sh AppService batchImportSN /v1/devService/batchImportSN
./add.sh AppService batchInsertUserAndOrg /v1/userService/batchInsertUserAndOrg
./add.sh AppService batchModifyDevicesInfoAndPropertis /v1/devService/batchModifyDevicesInfoAndPropertis
./add.sh AppService batchProcessPlantReport /v1/powerStationService/batchProcessPlantReport
./add.sh AppService batchUpdateDeviceSim /v1/devService/batchUpdateDeviceSim
./add.sh AppService batchUpdateUserIsAgreeGdpr /v1/userService/batchUpdateUserIsAgreeGdpr
./add.sh AppService boundMobilePhone /v1/userService/boundMobilePhone
./add.sh AppService boundUserMail /v1/userService/boundUserMail
./add.sh AppService caculateDeviceInputDiscrete /v1/devService/caculateDeviceInputDiscrete
./add.sh AppService calculateDeviceDiscrete /v1/devService/calculateDeviceDiscrete
./add.sh AppService calculateInitialCompensationData /v1/powerStationService/calculateInitialCompensationData
./add.sh AppService cancelDeliverMail /v1/messageService/cancelDeliverMail
./add.sh AppService cancelOrderScan /v1/devService/cancelOrderScan
./add.sh AppService cancelParamSetTask /v1/devService/cancelParamSetTask
./add.sh AppService cancelPsSharing /v1/powerStationService/cancelPsSharing
./add.sh AppService cancelRechargeOrder /onlinepay/cancelRechargeOrder
./add.sh AppService changRechargeOrderToCancel /onlinepay/changRechargeOrderToCancel
./add.sh AppService changeHouseholdUser2Installer /v1/orgService/changeHouseholdUser2Installer
./add.sh AppService changeRemoteParam /v1/devService/changeRemoteParam
./add.sh AppService checkDealerOrgCode /v1/orgService/checkDealerOrgCode
./add.sh AppService checkDevSnIsBelongsToUser /v1/userService/checkDevSnIsBelongsToUser
./add.sh AppService checkInverterResult /v1/devService/checkInverterResult
./add.sh AppService checkIsCanDoParamSet /v1/devService/checkIsCanDoParamSet
./add.sh AppService checkIsIvScan /v1/devService/checkIsIvScan
./add.sh AppService checkOssObjectExist /v1/commonService/checkOssObjectExist
./add.sh AppService checkServiceIsConnect /v1/commonService/checkServiceIsConnect
./add.sh AppService checkTechnicalParameters /v1/devService/checkTechnicalParameters
./add.sh AppService checkUpRechargeDevicePaying /onlinepay/checkUpRechargeDevicePaying
./add.sh AppService checkUserAccountUnique /v1/userService/checkUserAccountUnique
./add.sh AppService checkUserAccountUniqueAll /v1/userService/checkUserAccountUniqueAll
./add.sh AppService checkUserInfoUnique /v1/userService/checkUserInfoUnique
./add.sh AppService checkUserIsExist /v1/userService/checkUserIsExist
./add.sh AppService checkUserListIsExist /v1/userService/checkUserListIsExist
./add.sh AppService checkUserPassword /v1/userService/checkUserPassword
./add.sh AppService cloudDeploymentRecord /v1/commonService/cloudDeploymentRecord
./add.sh AppService comfirmParamModel /v1/devService/comfirmParamModel
./add.sh AppService compareValidateCode /v1/userService/compareValidateCode
./add.sh AppService componentInfo2Cloud /v1/devService/componentInfo2Cloud
./add.sh AppService confirmFault /v1/faultService/confirmFault
./add.sh AppService confirmIvFault /v1/devService/confirmIvFault
./add.sh AppService confirmReportConfig /v1/reportService/confirmReportConfig
./add.sh AppService createAppkeyInfo /v1/userService/createAppkeyInfo
./add.sh AppService createRenewInvoice /onlinepay/createRenewInvoice
./add.sh AppService dealCommandReply /devDataHandleService/dealCommandReply
./add.sh AppService dealDeletePsFailPsDelete /v1/powerStationService/dealDeletePsFailPsDelete
./add.sh AppService dealFailRemoteUpgradeSubTasks /v1/devService/dealFailRemoteUpgradeSubTasks
./add.sh AppService dealFailRemoteUpgradeTasks /v1/devService/dealFailRemoteUpgradeTasks
./add.sh AppService dealFaultOrder /v1/faultService/dealFaultOrder
./add.sh AppService dealGroupStringDisableOrEnable /v1/devService/dealGroupStringDisableOrEnable
./add.sh AppService dealNumberOfServiceCalls2Mysql /v1/commonService/dealNumberOfServiceCalls2Mysql
./add.sh AppService dealParamSettingAfterComplete /v1/devService/dealParamSettingAfterComplete
./add.sh AppService dealPsDataSupplement /v1/powerStationService/dealPsDataSupplement
./add.sh AppService dealPsReportEmailSend /v1/reportService/dealPsReportEmailSend
./add.sh AppService dealRemoteUpgrade /v1/devService/dealRemoteUpgrade
./add.sh AppService dealSnElectrifyCheck /v1/devService/dealSnElectrifyCheck
./add.sh AppService dealSysDeviceSimFlowInfo /v1/devService/dealSysDeviceSimFlowInfo
./add.sh AppService dealSysDeviceSimInfo /v1/devService/dealSysDeviceSimInfo
./add.sh AppService definiteTimeDealSnExpRemind /v1/devService/definiteTimeDealSnExpRemind
./add.sh AppService definiteTimeDealSnStatus /v1/devService/definiteTimeDealSnStatus
./add.sh AppService delDeviceRepair /v1/devService/delDeviceRepair
./add.sh AppService delOperRule /v1/faultService/delOperRule
./add.sh AppService delayCallApiResidueTimes /v1/commonService/delayCallApiResidueTimes
./add.sh AppService deleteComponent /v1/devService/deleteComponent
./add.sh AppService deleteCustomerEmployee /v1/devService/deleteCustomerEmployee
./add.sh AppService deleteDeviceAccount /v1/devService/deleteDeviceAccount
./add.sh AppService deleteDeviceSimById /v1/devService/deleteDeviceSimById
./add.sh AppService deleteElectricitySettlementData /v1/otherService/deleteElectricitySettlementData
./add.sh AppService deleteFaultPlan /v1/faultService/deleteFaultPlan
./add.sh AppService deleteFirmwareFiles /v1/commonService/deleteFirmwareFiles
./add.sh AppService deleteHouseholdEvaluation /v1/faultService/deleteHouseholdEvaluation
./add.sh AppService deleteHouseholdLeaveMessage /v1/faultService/deleteHouseholdLeaveMessage
./add.sh AppService deleteHouseholdWorkOrder /v1/faultService/deleteHouseholdWorkOrder
./add.sh AppService deleteInverterSnInChnnl /devDataHandleService/deleteInverterSnInChnnl
./add.sh AppService deleteModuleLog /integrationService/deleteModuleLog
./add.sh AppService deleteOnDutyInfo /v1/otherService/deleteOnDutyInfo
./add.sh AppService deleteOperateBillFile /v1/faultService/deleteOperateBillFile
./add.sh AppService deleteOssObject /v1/commonService/deleteOssObject
./add.sh AppService deletePowerDevicePointById /v1/reportService/deletePowerDevicePointById
./add.sh AppService deletePowerPicture /v1/powerStationService/deletePowerPicture
./add.sh AppService deletePowerRobotInfoBySnAndPsId /v1/devService/deletePowerRobotInfoBySnAndPsId
./add.sh AppService deletePowerRobotSweepStrategy /v1/devService/deletePowerRobotSweepStrategy
./add.sh AppService deleteProductionData /v1/devService/deleteProductionData
./add.sh AppService deletePs /v1/powerStationService/deletePs
./add.sh AppService deleteRechargeOrder /onlinepay/deleteRechargeOrder
./add.sh AppService deleteRegularlyConnectionInfo /v1/commonService/deleteRegularlyConnectionInfo
./add.sh AppService deleteReportConfigEmailAddr /v1/reportService/deleteReportConfigEmailAddr
./add.sh AppService deleteSysAdvancedParam /v1/devService/deleteSysAdvancedParam
./add.sh AppService deleteSysOrgNew /v1/otherService/deleteSysOrgNew
./add.sh AppService deleteTemplate /v1/devService/deleteTemplate
./add.sh AppService deleteUserInfoAllByUserId /v1/userService/deleteUserInfoAllByUserId
./add.sh AppService deviceInputDiscreteDeleteTime /v1/devService/deviceInputDiscreteDeleteTime
./add.sh AppService deviceInputDiscreteGetTime /v1/devService/deviceInputDiscreteGetTime
./add.sh AppService deviceInputDiscreteInsertTime /v1/devService/deviceInputDiscreteInsertTime
./add.sh AppService deviceInputDiscreteUpdateTime /v1/devService/deviceInputDiscreteUpdateTime
./add.sh AppService deviceReplace /v1/devService/deviceReplace
./add.sh AppService editDeviceRepair /v1/devService/editDeviceRepair
./add.sh AppService editOperRule /v1/faultService/editOperRule
./add.sh AppService energyPovertyAlleviation /v1/orgService/energyPovertyAlleviation
./add.sh AppService faultAutoClose /v1/faultService/faultAutoClose
./add.sh AppService faultCloseRemindOrderHandler /v1/faultService/faultCloseRemindOrderHandler
./add.sh AppService findCodeValueList /v1/commonService/findCodeValueList
./add.sh AppService findEmgOrgInfo /v1/otherService/findEmgOrgInfo
./add.sh AppService findEnvironmentInfo /v1/devService/findEnvironmentInfo
./add.sh AppService findFromHbaseAndRedis /v1/commonService/findFromHbaseAndRedis
./add.sh AppService findLossAnalysisList /v1/powerStationService/findLossAnalysisList
./add.sh AppService findOnDutyInfo /v1/otherService/findOnDutyInfo
./add.sh AppService findSingleStationPR /v1/powerStationService/findSingleStationPR
./add.sh AppService findUserPassword /v1/devService/findUserPassword
./add.sh AppService genTLSUserSigByUserAccount /v1/userService/genTLSUserSigByUserAccount
./add.sh AppService generateRandomPassword /v1/userService/generateRandomPassword
./add.sh AppService getAPIServiceInfo /v1/commonService/getAPIServiceInfo
./add.sh AppService getAccessedPermission /v1/commonService/getAccessedPermission
./add.sh AppService getAllDeviceByPsId /v1/devService/getAllDeviceByPsId
./add.sh AppService getAllPowerRobotViewInfoByPsId /v1/devService/getAllPowerRobotViewInfoByPsId
./add.sh AppService getAllPsIdByOrgIds /v1/devService/getAllPsIdByOrgIds
./add.sh AppService getAllUserRemindCount /v1/devService/getAllUserRemindCount
./add.sh AppService getAndOutletsAndUnit /v1/devService/getAndOutletsAndUnit
./add.sh AppService getAreaInfoCodeByCounty /v1/commonService/getAreaInfoCodeByCounty
./add.sh AppService getAreaList /v1/powerStationService/getAreaList
./add.sh AppService getAutoCreatePowerStation /v1/powerStationService/getAutoCreatePowerStation
./add.sh AppService getBackReadValue /v1/devService/getBackReadValue
./add.sh AppService getBatchNewestPointData /v1/devService/getBatchNewestPointData
./add.sh AppService getCallApiResidueTimes /v1/commonService/getCallApiResidueTimes
./add.sh AppService getChangedPsListByTime /v1/powerStationService/getChangedPsListByTime
./add.sh AppService getChnnlListByPsId /v1/devService/getChnnlListByPsId
./add.sh AppService getCloudList /v1/commonService/getCloudList
./add.sh AppService getCloudServiceMappingConfig /v1/commonService/getCloudServiceMappingConfig
./add.sh AppService getCommunicationDeviceConfigInfo /v1/devService/getCommunicationDeviceConfigInfo
./add.sh AppService getCommunicationModuleMonitorData /v1/devService/getCommunicationModuleMonitorData
./add.sh AppService getComponentModelFactory /v1/devService/getComponentModelFactory
./add.sh AppService getConfigList /devDataHandleService/getConfigList
./add.sh AppService getConnectionInfoBySnAndLocalPort /v1/commonService/getConnectionInfoBySnAndLocalPort
./add.sh AppService getCountDown /v1/devService/getCountDown
./add.sh AppService getCountryServiceInfo /v1/commonService/getCountryServiceInfo
./add.sh AppService getCounty /v1/commonService/getCounty
./add.sh AppService getCustomerEmployee /v1/devService/getCustomerEmployee
./add.sh AppService getCustomerList /v1/devService/getCustomerList
./add.sh AppService getDevInstalledPowerByPsId /v1/devService/getDevInstalledPowerByPsId
./add.sh AppService getDevRecord /v1/devService/getDevRecord
./add.sh AppService getDevRunRecordList /v1/devService/getDevRunRecordList
./add.sh AppService getDevSimByList /v1/devService/getDevSimByList
./add.sh AppService getDevSimList /v1/devService/getDevSimList
./add.sh AppService getDeviceAccountById /v1/devService/getDeviceAccountById
./add.sh AppService getDeviceFaultStatisticsData /v1/devService/getDeviceFaultStatisticsData
./add.sh AppService getDeviceInfo /v1/devService/getDeviceInfo
./add.sh AppService getDeviceList /v1/devService/getDeviceList
./add.sh AppService getDeviceModelInfoList /v1/devService/getDeviceModelInfoList
./add.sh AppService getDevicePropertys /v1/devService/getDevicePropertys
./add.sh AppService getDeviceRepairDetail /v1/devService/getDeviceRepairDetail
./add.sh AppService getDeviceTechBranchCount /v1/devService/getDeviceTechBranchCount
./add.sh AppService getDeviceTypeInfoList /v1/devService/getDeviceTypeInfoList
./add.sh AppService getDeviceTypeList /v1/devService/getDeviceTypeList
./add.sh AppService getDstInfo /v1/userService/getDstInfo
./add.sh AppService getElectricitySettlementData /v1/otherService/getElectricitySettlementData
./add.sh AppService getElectricitySettlementDetailData /v1/otherService/getElectricitySettlementDetailData
./add.sh AppService getEncryptPublicKey /v1/commonService/getEncryptPublicKey
./add.sh AppService getFaultCount /v1/faultService/getFaultCount
./add.sh AppService getFaultDetail /v1/faultService/getFaultDetail
./add.sh AppService getFaultMsgByFaultCode /v1/faultService/getFaultMsgByFaultCode
./add.sh AppService getFaultMsgListByPageWithYYYYMM /v1/faultService/getFaultMsgListByPageWithYYYYMM
./add.sh AppService getFaultMsgListWithYYYYMM /v1/faultService/getFaultMsgListWithYYYYMM
./add.sh AppService getFaultPlanList /v1/faultService/getFaultPlanList
./add.sh AppService getFileOperationRecordOne /v1/commonService/getFileOperationRecordOne
./add.sh AppService getFormulaFaultAnalyseList /v1/powerStationService/getFormulaFaultAnalyseList
./add.sh AppService getGroupStringCheckResult /v1/devService/getGroupStringCheckResult
./add.sh AppService getGroupStringCheckRule /v1/devService/getGroupStringCheckRule
./add.sh AppService getHisData /v1/devService/getHisData
./add.sh AppService getHouseholdEvaluation /v1/faultService/getHouseholdEvaluation
./add.sh AppService getHouseholdLeaveMessage /v1/faultService/getHouseholdLeaveMessage
./add.sh AppService getHouseholdOpinionFeedback /v1/faultService/getHouseholdOpinionFeedback
./add.sh AppService getHouseholdPsInstallerByUserId /v1/userService/getHouseholdPsInstallerByUserId
./add.sh AppService getHouseholdUserInfo /v1/userService/getHouseholdUserInfo
./add.sh AppService getHouseholdWorkOrderInfo /v1/faultService/getHouseholdWorkOrderInfo
./add.sh AppService getHouseholdWorkOrderList /v1/faultService/getHouseholdWorkOrderList
./add.sh AppService getI18nConfigByType /integrationService/i18nfile/getI18nConfigByType
./add.sh AppService getI18nFileInfo /integrationService/i18nfile/getI18nFileInfo
./add.sh AppService getI18nInfoByKey /integrationService/i18nfile/getI18nInfoByKey
./add.sh AppService getI18nVersion /integrationService/international/getI18nVersion
./add.sh AppService getIncomeSettingInfos /v1/powerStationService/getIncomeSettingInfos
./add.sh AppService getInfoFromAMap /v1/commonService/getInfoFromAMap
./add.sh AppService getInfomationFromRedis /v1/devService/getInfomationFromRedis
./add.sh AppService getInstallInfoList /v1/orgService/getInstallInfoList
./add.sh AppService getInstallerInfoByDealerOrgCodeOrId /v1/orgService/getInstallerInfoByDealerOrgCodeOrId
./add.sh AppService getInvertDataList /v1/devService/getInvertDataList
./add.sh AppService getInverterDataCount /v1/devService/getInverterDataCount
./add.sh AppService getInverterProcess /v1/devService/getInverterProcess
./add.sh AppService getInverterUuidBytotalId /v1/devService/getInverterUuidBytotalId
./add.sh AppService getIvEchartsData /v1/devService/getIvEchartsData
./add.sh AppService getIvEchartsDataById /v1/devService/getIvEchartsDataById
./add.sh AppService getKpiInfo /v1/powerStationService/getKpiInfo
./add.sh AppService getMapInfo /v1/powerStationService/getMapInfo
./add.sh AppService getMenuAndPrivileges /v1/userService/getMenuAndPrivileges
./add.sh AppService getMicrogridEStoragePsReport /v1/powerStationService/getMicrogridEStoragePsReport
./add.sh AppService getModuleLogInfo /integrationService/getModuleLogInfo
./add.sh AppService getNationProvJSON /v1/commonService/getNationProvJSON
./add.sh AppService getNeedOpAsynOpRecordList /v1/commonService/getNeedOpAsynOpRecordList
./add.sh AppService getNoticeInfo /v1/otherService/getNoticeInfo
./add.sh AppService getNumberOfServiceCalls /v1/commonService/getNumberOfServiceCalls
./add.sh AppService getOSSConfig /v1/commonService/getOSSConfig
./add.sh AppService getOperRuleDetail /v1/faultService/getOperRuleDetail
./add.sh AppService getOperateBillFileId /v1/faultService/getOperateBillFileId
./add.sh AppService getOperateTicketForDetail /v1/faultService/getOperateTicketForDetail
./add.sh AppService getOrCreateNetEaseUserToken /v1/userService/getOrCreateNetEaseUserToken
./add.sh AppService getOrderDataList /v1/faultService/getOrderDataList
./add.sh AppService getOrderDataSql2 /v1/devService/getOrderDataSql2
./add.sh AppService getOrderDatas /v1/devService/getOrderDatas
./add.sh AppService getOrderDetail /v1/faultService/getOrderDetail
./add.sh AppService getOrderStatistics /v1/faultService/getOrderStatistics
./add.sh AppService getOrgIdNameByUserId /v1/orgService/getOrgIdNameByUserId
./add.sh AppService getOrgInfoByDealerOrgCode /v1/orgService/getOrgInfoByDealerOrgCode
./add.sh AppService getOrgListByName /v1/orgService/getOrgListByName
./add.sh AppService getOrgListByUserId /v1/userService/getOrgListByUserId
./add.sh AppService getOrgListForUser /v1/orgService/getOrgListForUser
./add.sh AppService getOssObjectStream /v1/commonService/getOssObjectStream
./add.sh AppService getOwnerFaultConfigList /v1/faultService/getOwnerFaultConfigList
./add.sh AppService getParamSetTemplate4NewProtocol /v1/devService/getParamSetTemplate4NewProtocol
./add.sh AppService getParamSetTemplatePointInfo /v1/devService/getParamSetTemplatePointInfo
./add.sh AppService getParamterSettingBase /v1/devService/getParamterSettingBase
./add.sh AppService getPhotoInfo /v1/otherService/getPhotoInfo
./add.sh AppService getPlanedOrNotPsList /v1/faultService/getPlanedOrNotPsList
./add.sh AppService getPlantReportPDFList /v1/powerStationService/getPlantReportPDFList
./add.sh AppService getPowerChargeSettingInfo /v1/powerStationService/getPowerChargeSettingInfo
./add.sh AppService getPowerDeviceModelTechList /v1/devService/getPowerDeviceModelTechList
./add.sh AppService getPowerDeviceModelTree /v1/devService/getPowerDeviceModelTree
./add.sh AppService getPowerDevicePointInfo /v1/reportService/getPowerDevicePointInfo
./add.sh AppService getPowerFormulaFaultAnalyse /v1/powerStationService/getPowerFormulaFaultAnalyse
./add.sh AppService getPowerPictureList /v1/powerStationService/getPowerPictureList
./add.sh AppService getPowerRobotInfoByRobotSn /v1/devService/getPowerRobotInfoByRobotSn
./add.sh AppService getPowerRobotSweepAttrByPsId /v1/devService/getPowerRobotSweepAttrByPsId
./add.sh AppService getPowerRobotSweepStrategy /v1/devService/getPowerRobotSweepStrategy
./add.sh AppService getPowerRobotSweepStrategyList /v1/devService/getPowerRobotSweepStrategyList
./add.sh AppService getPowerSettingCharges /v1/powerStationService/getPowerSettingCharges
./add.sh AppService getPowerSettingHistoryRecords /v1/powerStationService/getPowerSettingHistoryRecords
./add.sh AppService getPowerStationBasicInfo /v1/powerStationService/getPowerStationBasicInfo
./add.sh AppService getPowerStationData /v1/powerStationService/getPowerStationData
./add.sh AppService getPowerStationForHousehold /v1/powerStationService/getPowerStationForHousehold
./add.sh AppService getPowerStationInfo /v1/powerStationService/getPowerStationInfo
./add.sh AppService getPowerStationPR /v1/powerStationService/getPowerStationPR
./add.sh AppService getPrivateCloudValidityPeriod /v1/commonService/getPrivateCloudValidityPeriod
./add.sh AppService getProvInfoListByNationCode /v1/commonService/getProvInfoListByNationCode
./add.sh AppService getPsDetailByUserTokens /v1/powerStationService/getPsDetailByUserTokens
./add.sh AppService getPsDetailForSinglePage /v1/powerStationService/getPsDetailForSinglePage
./add.sh AppService getPsInstallerByPsId /v1/orgService/getPsInstallerByPsId
./add.sh AppService getPsInstallerOrgInfoByPsId /v1/powerStationService/getPsInstallerOrgInfoByPsId
./add.sh AppService getPsListByName /v1/powerStationService/getPsListByName
./add.sh AppService getPsListForPsDataByPsId /v1/powerStationService/getPsListForPsDataByPsId
./add.sh AppService getPsListStaticData /v1/powerStationService/getPsListStaticData
./add.sh AppService getPsReport /v1/reportService/getPsReport
./add.sh AppService getPsUser /v1/userService/getPsUser
./add.sh AppService getPsWeatherList /v1/powerStationService/getPsWeatherList
./add.sh AppService getRechargeOrderDetail /onlinepay/getRechargeOrderDetail
./add.sh AppService getRechargeOrderItemDeviceList /onlinepay/getRechargeOrderItemDeviceList
./add.sh AppService getRechargeOrderList /onlinepay/getRechargeOrderList
./add.sh AppService getRegionalTree /v1/orgService/getRegionalTree
./add.sh AppService getRemoteParamSettingList /v1/devService/getRemoteParamSettingList
./add.sh AppService getRemoteUpgradeDeviceList /v1/devService/getRemoteUpgradeDeviceList
./add.sh AppService getRemoteUpgradeScheduleDetails /v1/devService/getRemoteUpgradeScheduleDetails
./add.sh AppService getRemoteUpgradeSubTasksList /v1/devService/getRemoteUpgradeSubTasksList
./add.sh AppService getRemoteUpgradeTaskList /v1/devService/getRemoteUpgradeTaskList
./add.sh AppService getReportData /v1/powerStationService/getReportData
./add.sh AppService getReportEmailConfigInfo /v1/reportService/getReportEmailConfigInfo
./add.sh AppService getReportExportColumns /v1/reportService/getReportExportColumns
./add.sh AppService getReportListByUserId /v1/reportService/getReportListByUserId
./add.sh AppService getRobotDynamicCleaningView /v1/devService/getRobotDynamicCleaningView
./add.sh AppService getRobotNumAndSweepCapacity /v1/devService/getRobotNumAndSweepCapacity
./add.sh AppService getRuleUnit /v1/powerStationService/getRuleUnit
./add.sh AppService getSendReportConfigCron /v1/reportService/getSendReportConfigCron
./add.sh AppService getShieldMapConditionList /v1/commonService/getShieldMapConditionList
./add.sh AppService getSimIdBySnList /v1/devService/getSimIdBySnList
./add.sh AppService getSingleIVData /v1/devService/getSingleIVData
./add.sh AppService getSnChangeRecord /v1/devService/getSnChangeRecord
./add.sh AppService getSnConnectionInfo /v1/commonService/getSnConnectionInfo
./add.sh AppService getSungwsConfigCache /v1/commonService/getSungwsConfigCache
./add.sh AppService getSungwsGlobalConfigCache /v1/commonService/getSungwsGlobalConfigCache
./add.sh AppService getSweepDevParamSetTemplate /v1/devService/getSweepDevParamSetTemplate
./add.sh AppService getSweepRobotDevList /v1/devService/getSweepRobotDevList
./add.sh AppService getSysMsg /v1/otherService/getSysMsg
./add.sh AppService getSysOrgNewList /v1/otherService/getSysOrgNewList
./add.sh AppService getSysOrgNewOne /v1/otherService/getSysOrgNewOne
./add.sh AppService getSysUserById /v1/userService/getSysUserById
./add.sh AppService getUUIDByUpuuid /v1/devService/getUUIDByUpuuid
./add.sh AppService getUserById /v1/userService/getUserById
./add.sh AppService getUserByInstaller /v1/userService/getUserByInstaller
./add.sh AppService getUserDevOnlineOffineCount /v1/devService/getUserDevOnlineOffineCount
./add.sh AppService getUserGDPRAttrs /v1/userService/getUserGDPRAttrs
./add.sh AppService getUserHavePowerStationCount /v1/userService/getUserHavePowerStationCount
./add.sh AppService getUserInfoByUserAccounts /v1/userService/getUserInfoByUserAccounts
./add.sh AppService getUserList /v1/userService/getUserList
./add.sh AppService getUserPsOrderList /v1/faultService/getUserPsOrderList
./add.sh AppService getValidateCode /v1/userService/getValidateCode
./add.sh AppService getValidateCodeAtRegister /v1/userService/getValidateCodeAtRegister
./add.sh AppService getWeatherInfo /v1/powerStationService/getWeatherInfo
./add.sh AppService getWechatPushConfig /v1/userService/getWechatPushConfig
./add.sh AppService getWorkInfo /v1/otherService/getWorkInfo
./add.sh AppService groupStringCheck /v1/devService/groupStringCheck
./add.sh AppService handleDevByCommunicationSN /devDataHandleService/handleDevByCommunicationSN
./add.sh AppService householdResetPassBySN /v1/userService/householdResetPassBySN
./add.sh AppService immediatePayment /onlinepay/immediatePayment
./add.sh AppService importExcelData /v1/devService/importExcelData
./add.sh AppService incomeStatistics /v1/powerStationService/incomeStatistics
./add.sh AppService informPush /v1/messageService/informPush
./add.sh AppService insertEmgOrgInfo /v1/otherService/insertEmgOrgInfo
./add.sh AppService insightSynDeviceStructure2Cloud /v1/powerStationService/insightSynDeviceStructure2Cloud
./add.sh AppService intoDataToHbase /v1/commonService/intoDataToHbase
./add.sh AppService ipLocationQuery /v1/commonService/ipLocationQuery
./add.sh AppService isHave2GSn /v1/devService/isHave2GSn
./add.sh AppService judgeDevIsHasInitSetTemplate /v1/devService/judgeDevIsHasInitSetTemplate
./add.sh AppService judgeIsSettingMan /v1/faultService/judgeIsSettingMan
./add.sh AppService listOssFiles /v1/commonService/listOssFiles
./add.sh AppService loadAreaInfo /v1/commonService/loadAreaInfo
./add.sh AppService loadPowerStation /v1/powerStationService/loadPowerStation
./add.sh AppService loginByToken /v1/userService/loginByToken
./add.sh AppService logout /v1/userService/logout
./add.sh AppService mobilePhoneHasBound /v1/userService/mobilePhoneHasBound
./add.sh AppService modifiedDeviceInfo /v1/devService/modifiedDeviceInfo
./add.sh AppService modifyEmgOrgStruc /v1/otherService/modifyEmgOrgStruc
./add.sh AppService modifyFaultPlan /v1/faultService/modifyFaultPlan
./add.sh AppService modifyOnDutyInfo /v1/otherService/modifyOnDutyInfo
./add.sh AppService modifyPassword /v1/userService/modifyPassword
./add.sh AppService modifyPersonalUnitList /v1/userService/modifyPersonalUnitList
./add.sh AppService modifyPsUser /v1/userService/modifyPsUser
./add.sh AppService moduleLogParamSet /integrationService/moduleLogParamSet
./add.sh AppService operateOssFile /v1/commonService/operateOssFile
./add.sh AppService operationPowerRobotSweepStrategy /v1/devService/operationPowerRobotSweepStrategy
./add.sh AppService orgPowerReport /v1/orgService/orgPowerReport
./add.sh AppService paramSetTryAgain /v1/devService/paramSetTryAgain
./add.sh AppService paramSetting /v1/devService/paramSetting
./add.sh AppService planPower /v1/powerStationService/planPower
./add.sh AppService psForcastInfo /v1/powerStationService/psForcastInfo
./add.sh AppService queryBatchSpeedyAddPowerStationResult /v1/powerStationService/queryBatchSpeedyAddPowerStationResult
./add.sh AppService queryCardStatusCTCC /v1/devService/queryCardStatusCTCC
./add.sh AppService queryChildAccountList /v1/userService/queryChildAccountList
./add.sh AppService queryCompensationRecordData /v1/powerStationService/queryCompensationRecordData
./add.sh AppService queryCompensationRecordList /v1/powerStationService/queryCompensationRecordList
./add.sh AppService queryComponent /v1/devService/queryComponent
./add.sh AppService queryComponentTechnicalParam /v1/devService/queryComponentTechnicalParam
./add.sh AppService queryCountryGridAndRelation /v1/devService/queryCountryGridAndRelation
./add.sh AppService queryCountryList /v1/commonService/queryCountryList
./add.sh AppService queryDeviceRepairList /v1/devService/queryDeviceRepairList
./add.sh AppService queryDeviceTypeInfoList /v1/devService/queryDeviceTypeInfoList
./add.sh AppService queryEnvironmentList /v1/devService/queryEnvironmentList
./add.sh AppService queryFaultList /v1/faultService/queryFaultList
./add.sh AppService queryFaultPlanDetail /v1/faultService/queryFaultPlanDetail
./add.sh AppService queryFaultRepairSteps /v1/faultService/queryFaultRepairSteps
./add.sh AppService queryFaultTypeAndLevelByCode /v1/faultService/queryFaultTypeAndLevelByCode
./add.sh AppService queryFaultTypeByDevice /v1/faultService/queryFaultTypeByDevice
./add.sh AppService queryFaultTypeByDevicePage /v1/faultService/queryFaultTypeByDevicePage
./add.sh AppService queryFirmwareFilesPage /v1/commonService/queryFirmwareFilesPage
./add.sh AppService queryInfotoAlert /v1/devService/queryInfotoAlert
./add.sh AppService queryInverterModelList /v1/devService/queryInverterModelList
./add.sh AppService queryInverterVersionList /v1/devService/queryInverterVersionList
./add.sh AppService queryM2MCardInfoCMCC /v1/devService/queryM2MCardInfoCMCC
./add.sh AppService queryM2MCardTermInfoCMCC /v1/devService/queryM2MCardTermInfoCMCC
./add.sh AppService queryModelInfoByModelId /v1/devService/queryModelInfoByModelId
./add.sh AppService queryNoticeList /v1/otherService/queryNoticeList
./add.sh AppService queryNumberOfRenewalReminders /v1/devService/queryNumberOfRenewalReminders
./add.sh AppService queryOperRules /v1/faultService/queryOperRules
./add.sh AppService queryOrderList /v1/faultService/queryOrderList
./add.sh AppService queryOrderStep /v1/faultService/queryOrderStep
./add.sh AppService queryOrgGenerationReport /v1/orgService/queryOrgGenerationReport
./add.sh AppService queryOrgInfoList /v1/userService/queryOrgInfoList
./add.sh AppService queryOrgPowerElecPercent /v1/orgService/queryOrgPowerElecPercent
./add.sh AppService queryOrgPsCompensationRecordList /v1/powerStationService/queryOrgPsCompensationRecordList
./add.sh AppService queryPersonalUnitList /v1/userService/queryPersonalUnitList
./add.sh AppService queryPointDataTopOne /v1/devService/queryPointDataTopOne
./add.sh AppService queryPowerStationInfo /v1/powerStationService/queryPowerStationInfo
./add.sh AppService queryPsAreaByUserIdAndAreaCode /v1/powerStationService/queryPsAreaByUserIdAndAreaCode
./add.sh AppService queryPsCompensationRecordList /v1/powerStationService/queryPsCompensationRecordList
./add.sh AppService queryPsDataByDate /v1/powerStationService/queryPsDataByDate
./add.sh AppService queryPsIdList /v1/powerStationService/queryPsIdList
./add.sh AppService queryPsListByUserIdAndAreaCode /v1/powerStationService/queryPsListByUserIdAndAreaCode
./add.sh AppService queryPsNameByPsId /v1/devService/queryPsNameByPsId
./add.sh AppService queryPsPrByDate /v1/powerStationService/queryPsPrByDate
./add.sh AppService queryPsProfit /v1/powerStationService/queryPsProfit
./add.sh AppService queryPsReportComparativeAnalysisOfPowerGeneration /v1/powerStationService/queryPsReportComparativeAnalysisOfPowerGeneration
./add.sh AppService queryPsStructureList /v1/devService/queryPsStructureList
./add.sh AppService queryPuuidsByCommandTotalId /v1/devService/queryPuuidsByCommandTotalId
./add.sh AppService queryPuuidsByCommandTotalId2 /v1/devService/queryPuuidsByCommandTotalId2
./add.sh AppService queryRepairRuleList /v1/devService/queryRepairRuleList
./add.sh AppService queryReportListForManagementPage /v1/reportService/queryReportListForManagementPage
./add.sh AppService queryReportMsg /v1/reportService/queryReportMsg
./add.sh AppService querySharingPs /v1/powerStationService/querySharingPs
./add.sh AppService querySysAdvancedParam /v1/devService/querySysAdvancedParam
./add.sh AppService queryTimeBySN /v1/devService/queryTimeBySN
./add.sh AppService queryTrafficByDateCTCC /v1/devService/queryTrafficByDateCTCC
./add.sh AppService queryTrafficCTCC /v1/devService/queryTrafficCTCC
./add.sh AppService queryUnitUuidBytotalId /v1/devService/queryUnitUuidBytotalId
./add.sh AppService queryUserBtnPri /v1/userService/queryUserBtnPri
./add.sh AppService queryUserByUserIds /v1/userService/queryUserByUserIds
./add.sh AppService queryUserExtensionAttribute /v1/userService/queryUserExtensionAttribute
./add.sh AppService queryUserForStep /v1/userService/queryUserForStep
./add.sh AppService queryUserList /v1/userService/queryUserList
./add.sh AppService queryUserProcessPri /v1/userService/queryUserProcessPri
./add.sh AppService queryUserWechatBindRel /v1/userService/queryUserWechatBindRel
./add.sh AppService queryUuidByTotalIdAndUuid /v1/devService/queryUuidByTotalIdAndUuid
./add.sh AppService rechargeOrderSetMeal /v1/devService/rechargeOrderSetMeal
./add.sh AppService renewSendReportConfirmEmail /v1/reportService/renewSendReportConfirmEmail
./add.sh AppService reportList /v1/powerStationService/reportList
./add.sh AppService saveCustomerEmployee /v1/devService/saveCustomerEmployee
./add.sh AppService saveDevSimList /v1/devService/saveDevSimList
./add.sh AppService saveDeviceAccountBatchData /v1/devService/saveDeviceAccountBatchData
./add.sh AppService saveEnviromentIncomeInfos /v1/powerStationService/saveEnviromentIncomeInfos
./add.sh AppService saveEnvironmentCurve /v1/devService/saveEnvironmentCurve
./add.sh AppService saveFirmwareFile /v1/commonService/saveFirmwareFile
./add.sh AppService saveIncomeSettingInfos /v1/powerStationService/saveIncomeSettingInfos
./add.sh AppService saveOrUpdateGroupStringCheckRule /v1/devService/saveOrUpdateGroupStringCheckRule
./add.sh AppService saveParamModel /v1/devService/saveParamModel
./add.sh AppService savePowerCharges /v1/powerStationService/savePowerCharges
./add.sh AppService savePowerDevicePoint /v1/reportService/savePowerDevicePoint
./add.sh AppService savePowerRobotInfo /v1/devService/savePowerRobotInfo
./add.sh AppService savePowerRobotSweepAttr /v1/devService/savePowerRobotSweepAttr
./add.sh AppService savePowerSettingCharges /v1/powerStationService/savePowerSettingCharges
./add.sh AppService savePowerSettingInfo /v1/powerStationService/savePowerSettingInfo
./add.sh AppService saveProductionBatchData /v1/devService/saveProductionBatchData
./add.sh AppService saveRechargeOrderObj /onlinepay/saveRechargeOrderObj
./add.sh AppService saveRechargeOrderOtherInfo /onlinepay/saveRechargeOrderOtherInfo
./add.sh AppService saveRepair /v1/faultService/saveRepair
./add.sh AppService saveReportExportColumns /v1/reportService/saveReportExportColumns
./add.sh AppService saveSetParam /v1/devService/saveSetParam
./add.sh AppService saveSysUserMsg /v1/otherService/saveSysUserMsg
./add.sh AppService saveTemplate /v1/devService/saveTemplate
./add.sh AppService searchM2MMonthFlowCMCC /v1/devService/searchM2MMonthFlowCMCC
./add.sh AppService selectSysTranslationNames /v1/reportService/selectSysTranslationNames
./add.sh AppService sendPsTimeZoneInstruction /devDataHandleService/sendPsTimeZoneInstruction
./add.sh AppService setUpFormulaFaultAnalyse /v1/powerStationService/setUpFormulaFaultAnalyse
./add.sh AppService setUserGDPRAttrs /v1/userService/setUserGDPRAttrs
./add.sh AppService settingNotice /v1/userService/settingNotice
./add.sh AppService shareMyPs /v1/powerStationService/shareMyPs
./add.sh AppService sharePsBySN /v1/powerStationService/sharePsBySN
./add.sh AppService showInverterByUnit /v1/devService/showInverterByUnit
./add.sh AppService showOnlineUsers /v1/userService/showOnlineUsers
./add.sh AppService showWarning /v1/userService/showWarning
./add.sh AppService snIsExist /v1/devService/snIsExist
./add.sh AppService snsIsExist /v1/devService/snsIsExist
./add.sh AppService speedyAddPowerStation /v1/powerStationService/speedyAddPowerStation
./add.sh AppService stationDeviceHistoryDataList /v1/powerStationService/stationDeviceHistoryDataList
./add.sh AppService stationUnitsList /v1/powerStationService/stationUnitsList
./add.sh AppService stationsDiscreteData /v1/devService/stationsDiscreteData
./add.sh AppService stationsIncomeList /v1/powerStationService/stationsIncomeList
./add.sh AppService stationsPointReport /v1/powerStationService/stationsPointReport
./add.sh AppService stationsYearPlanReport /v1/reportService/stationsYearPlanReport
./add.sh AppService sureAndImportSelettlementData /v1/otherService/sureAndImportSelettlementData
./add.sh AppService sweepDevParamSet /v1/devService/sweepDevParamSet
./add.sh AppService sweepDevRunControl /v1/devService/sweepDevRunControl
./add.sh AppService sweepDevStrategyIssue /v1/devService/sweepDevStrategyIssue
./add.sh AppService sysTimeZoneList /v1/commonService/sysTimeZoneList
./add.sh AppService unLockUser /v1/userService/unLockUser
./add.sh AppService unlockChildAccount /v1/userService/unlockChildAccount
./add.sh AppService updateCommunicationModuleState /v1/devService/updateCommunicationModuleState
./add.sh AppService updateDevInstalledPower /v1/devService/updateDevInstalledPower
./add.sh AppService updateFault /v1/faultService/updateFaultStatus
./add.sh AppService updateFaultData /v1/faultService/updateFaultData
./add.sh AppService updateFaultMsgByFaultCode /v1/faultService/updateFaultMsgByFaultCode
./add.sh AppService updateFaultStatus /v1/faultService/updateFaultStatus
./add.sh AppService updateHouseholdWorkOrder /v1/faultService/updateHouseholdWorkOrder
./add.sh AppService updateInverterSn2ModuleSn /devDataHandleService/updateInverterSn2ModuleSn
./add.sh AppService updateOperateTicketAttachmentId /v1/faultService/updateOperateTicketAttachmentId
./add.sh AppService updateOrderDeviceByCustomerService /onlinepay/updateOrderDeviceByCustomerService
./add.sh AppService updateOwnerFaultConfig /v1/faultService/updateOwnerFaultConfig
./add.sh AppService updateParamSettingSysMsg /v1/devService/updateParamSettingSysMsg
./add.sh AppService updatePlatformLevelFaultLevel /v1/faultService/updatePlatformLevelFaultLevel
./add.sh AppService updatePowerDevicePoint /v1/reportService/updatePowerDevicePoint
./add.sh AppService updatePowerRobotInfo /v1/devService/updatePowerRobotInfo
./add.sh AppService updatePowerRobotSweepAttr /v1/devService/updatePowerRobotSweepAttr
./add.sh AppService updatePowerStationForHousehold /v1/powerStationService/updatePowerStationForHousehold
./add.sh AppService updatePowerStationInfo /v1/powerStationService/updatePowerStationInfo
./add.sh AppService updatePowerUserInfo /v1/userService/updatePowerUserInfo
./add.sh AppService updateReportConfigByEmailAddr /v1/reportService/updateReportConfigByEmailAddr
./add.sh AppService updateShareAttr /v1/powerStationService/updateShareAttr
./add.sh AppService updateSnIsSureFlag /devDataHandleService/updateSnIsSureFlag
./add.sh AppService updateStationPics /v1/powerStationService/updateStationPics
./add.sh AppService updateSysAdvancedParam /v1/devService/updateSysAdvancedParam
./add.sh AppService updateSysOrgNew /v1/otherService/updateSysOrgNew
./add.sh AppService updateTemplate /v1/devService/updateDataCurveTemplate
./add.sh AppService updateUinfoNetEaseUser /v1/userService/updateUinfoNetEaseUser
./add.sh AppService updateUserExtensionAttribute /v1/userService/updateUserExtensionAttribute
./add.sh AppService updateUserLanguage /v1/userService/updateUserLanguage
./add.sh AppService updateUserPosition /v1/userService/updateUserPosition
./add.sh AppService updateUserUpOrg /v1/orgService/updateUserUpOrg
./add.sh AppService upgrade /v1/userService/upgrade
./add.sh AppService upgrate /v1/userService/upgrade
./add.sh AppService uploadFileToOss /v1/commonService/uploadFileToOss
./add.sh AppService userAgreeGdprProtocol /v1/userService/userAgreeGdprProtocol
./add.sh AppService userInfoUniqueCheck /v1/userService/userInfoUniqueCheck
./add.sh AppService userMailHasBound /v1/userService/userMailHasBound
./add.sh AppService userRegister /v1/userService/userRegister
