./add.sh WebAppService	addMaterial	/v1/otherService/addMaterial
./add.sh WebAppService	addOptTicketInfo	/v1/faultService/addOptTicketInfo
./add.sh WebAppService	addSpareParts	/v1/otherService/addSpareParts
./add.sh WebAppService	associateQueryFaultNames	/v1/faultService/associateQueryFaultNames
./add.sh WebAppService	auditPsDeviceCheck	/v1/devService/auditPsDeviceCheck
./add.sh WebAppService	calcOutputRankByDay	/v1/powerStationService/calcOutputRankByDay
./add.sh WebAppService	changeReadStatus	/v1/reportService/changeReadStatus
./add.sh WebAppService	checkMaterialName	/v1/otherService/checkMaterialName
./add.sh WebAppService	confirmFault	/v1/faultService/confirmOrCloseFault
./add.sh WebAppService	copeOperateTicket	/v1/faultService/copeOperateTicket
./add.sh WebAppService	copySecondTypeTicket	/v1/faultService/copySecondTypeTicket
./add.sh WebAppService	copyWorkTicket	/v1/faultService/copyWorkTicket
./add.sh WebAppService	delOptTicketInfo	/v1/faultService/delOptTicketInfo
./add.sh WebAppService	deleteDuty	/v1/otherService/deleteDuty
./add.sh WebAppService	deleteDutyMid	/v1/otherService/deleteDutyMid
./add.sh WebAppService	deleteMaterial	/v1/otherService/deleteMaterial
./add.sh WebAppService	deleteOrSharedSelfReport	/v1/reportService/deleteOrSharedSelfReport
./add.sh WebAppService	deleteSecondTypeTicket	/v1/faultService/deleteSecondTypeTicket
./add.sh WebAppService	deleteSparePartsById	/v1/otherService/deleteSparePartsById
./add.sh WebAppService	deleteWorkTicket	/v1/faultService/deleteWorkTicket
./add.sh WebAppService	deviceFactoryList	/v1/devService/deviceFactoryList
./add.sh WebAppService	dispartDataPageList	/v1/commonService/dispartDataPageList
./add.sh WebAppService	executeTask	/v1/faultService/executeTask
./add.sh WebAppService	findCurrentTask	/v1/faultService/findCurrentTask
./add.sh WebAppService	findDeviceMessageByPskey	/v1/devService/findDeviceMessageByPskey
./add.sh WebAppService	findFactoryMessage	/v1/devService/findFactoryMessage
./add.sh WebAppService	findImgResources	/v1/faultService/findImgResources
./add.sh WebAppService	findMateiralSubType	/v1/otherService/findMateiralSubType
./add.sh WebAppService	findMaterialById	/v1/otherService/findMaterialById
./add.sh WebAppService	findMyDealedCurrentTask	/v1/faultService/findMyDealedCurrentTask
./add.sh WebAppService	findMyDealedImgResources	/v1/faultService/findMyDealedImgResources
./add.sh WebAppService	findSeriesInverterData	/v1/devService/findSeriesInverterData
./add.sh WebAppService	findWebRole	/v1/userService/findWebRole
./add.sh WebAppService	getAllPsFaultCount	/v1/faultService/getAllPsFaultCount
./add.sh WebAppService	getAllPsFaultCountByUserId	/v1/faultService/getAllPsFaultCountByUserId
./add.sh WebAppService	getAllPsList	/v1/powerStationService/getAllPsList
./add.sh WebAppService	getAllStore	/v1/otherService/getAllStore
./add.sh WebAppService	getBaseDeviceInfo	/v1/devService/getBaseDeviceInfo
./add.sh WebAppService	getBoxData	/v1/devService/getBoxData
./add.sh WebAppService	getCBoxTree	/v1/devService/getCBoxTree
./add.sh WebAppService	getCheckDevTypeList	/v1/devService/getCheckDevTypeList
./add.sh WebAppService	getCheckUserList	/v1/userService/getCheckUserList
./add.sh WebAppService	getChildOrg	/v1/otherService/getChildOrg
./add.sh WebAppService	getCo	/v1/powerStationService/getCo
./add.sh WebAppService	getCodeTreeMap	/v1/commonService/getCodeTreeMap
./add.sh WebAppService	getDST	/v1/userService/getDST
./add.sh WebAppService	getDataCounts	/v1/commonService/getDataCounts
./add.sh WebAppService	getDataInfo	/v1/powerStationService/getDataInfo
./add.sh WebAppService	getDevList	/v1/devService/getDevList
./add.sh WebAppService	getDevName	/v1/devService/getDevName
./add.sh WebAppService	getDevTypeList	/v1/devService/getDevTypeList
./add.sh WebAppService	getDeviceDataList	/v1/reportService/getDeviceDataList
./add.sh WebAppService	getDeviceFactory	/v1/devService/getDeviceFactory
./add.sh WebAppService	getDeviceInfoForCheck	/v1/devService/getDeviceInfoForCheck
./add.sh WebAppService	getDevicePointAttrs	/v1/devService/getDevicePointAttrs
./add.sh WebAppService	getDeviceTreeChild	/v1/devService/getDeviceTreeChild
./add.sh WebAppService	getDeviceUuid	/v1/devService/getDeviceUuid
./add.sh WebAppService	getDutyInfoById	/v1/otherService/getDutyInfoById
./add.sh WebAppService	getDutyOrgZtree	/v1/otherService/getDutyOrgZtree
./add.sh WebAppService	getElecEffectList	/v1/faultService/getElecEffectList
./add.sh WebAppService	getEnvironmentInfo	/v1/devService/getEnvironmentInfo
./add.sh WebAppService	getFaultList	/v1/faultService/getFaultList
./add.sh WebAppService	getFaultName	/v1/faultService/getFaultName
./add.sh WebAppService	getFaultOrder	/v1/faultService/getFaultOrder
./add.sh WebAppService	getFaultOrderByOrderId	/v1/faultService/getFaultOrderByOrderId
./add.sh WebAppService	getFaultOrderList	/v1/faultService/getFaultOrderList
./add.sh WebAppService	getFaultOrderStepList	/v1/faultService/getFaultOrderStepList
./add.sh WebAppService	getHTRoleList	/v1/userService/getHTRoleList
./add.sh WebAppService	getHistoryComments	/v1/faultService/getHistoryComments
./add.sh WebAppService	getInfo	/v1/devService/getInfo
./add.sh WebAppService	getInverteTableListCount	/v1/devService/getInverteTableListCount
./add.sh WebAppService	getInverterDiscreteDistributioList	/v1/reportService/getInverterDiscreteDistributioList
./add.sh WebAppService	getInverterDiscreteList	/v1/reportService/getInverterDiscreteList
./add.sh WebAppService	getInverterFactoryList	/v1/reportService/getInverterFactoryList
./add.sh WebAppService	getInverterInfo	/v1/devService/getInverterInfo
./add.sh WebAppService	getLoadCurveList	/v1/reportService/getLoadCurveList
./add.sh WebAppService	getMultiPowers	/v1/devService/getMultiPowers
./add.sh WebAppService	getOndutyQuery	/v1/otherService/getOndutyQuery
./add.sh WebAppService	getOperateTicketUserList	/v1/faultService/getOperateTicketUserList
./add.sh WebAppService	getOptTicketsAttachments	/v1/faultService/getOptTicketsAttachments
./add.sh WebAppService	getOrderCount	/v1/faultService/getOrderCount
./add.sh WebAppService	getOrderData	/v1/faultService/getOrderData
./add.sh WebAppService	getOrderDataSize	/v1/faultService/getOrderDataSize
./add.sh WebAppService	getOrgPsEquipmentList	/v1/faultService/getOrgPsEquipmentList
./add.sh WebAppService	getOrgPsPowerGenerationSummaryReport	/v1/reportService/getOrgPsPowerGenerationSummaryReport
./add.sh WebAppService	getParentUidChain	/v1/devService/getParentUidChain
./add.sh WebAppService	getPowerKwhkwpList	/v1/powerStationService/getPowerKwhkwpList
./add.sh WebAppService	getPowerPrList	/v1/powerStationService/getPowerPrList
./add.sh WebAppService	getPowerPredictionInfo	/v1/reportService/getPowerPredictionInfo
./add.sh WebAppService	getPowerTrendDayData	/v1/powerStationService/getPowerTrendDayData
./add.sh WebAppService	getPowerTrendMonthData	/v1/powerStationService/getPowerTrendMonthData
./add.sh WebAppService	getPowerTrendYearData	/v1/powerStationService/getPowerTrendYearData
./add.sh WebAppService	getPowerValue	/v1/reportService/getPowerValue
./add.sh WebAppService	getPsBlock	/v1/devService/getPsBlock
./add.sh WebAppService	getPsBlockData	/v1/devService/getPsBlockData
./add.sh WebAppService	getPsBlockTree	/v1/devService/getPsBlockTree
./add.sh WebAppService	getPsBoxListCount	/v1/devService/getPsBoxListCount
./add.sh WebAppService	getPsCBoxDetail	/v1/devService/getPsCBoxDetail
./add.sh WebAppService	getPsContact	/v1/powerStationService/getPsContact
./add.sh WebAppService	getPsDataVal	/v1/devService/getPsDataVal
./add.sh WebAppService	getPsDeviceCheckList	/v1/devService/getPsDeviceCheckList
./add.sh WebAppService	getPsDeviceFaultList	/v1/faultService/getPsDeviceFaultList
./add.sh WebAppService	getPsFaultList	/v1/faultService/getPsFaultList
./add.sh WebAppService	getPsIdByUserId	/v1/powerStationService/getPsIdByUserId
./add.sh WebAppService	getPsIdState	/v1/powerStationService/getPsIdState
./add.sh WebAppService	getPsList	/v1/powerStationService/getPsListForWeb
./add.sh WebAppService	getPsListForWorkTicket	/v1/faultService/getPsListForWorkTicket
./add.sh WebAppService	getPsPictureMessage	/v1/powerStationService/getPsPictureMessage
./add.sh WebAppService	getPsTicketSizeAndClockNum	/v1/faultService/getPsTicketSizeAndClockNum
./add.sh WebAppService	getPsTree	/v1/devService/getPsTree
./add.sh WebAppService	getPsTreeChild	/v1/devService/getPsTreeChild
./add.sh WebAppService	getPsUserList	/v1/userService/getPsUserList
./add.sh WebAppService	getPsValue	/v1/powerStationService/getPsValue
./add.sh WebAppService	getPscSeriseData	/v1/devService/getPscSeriseData
./add.sh WebAppService	getReportInfoByReportId	/v1/reportService/getReportInfoByReportId
./add.sh WebAppService	getReportListByType	/v1/reportService/getReportListByType
./add.sh WebAppService	getReportPsTree	/v1/reportService/getReportPsTree
./add.sh WebAppService	getRoleList	/v1/userService/getRoleList
./add.sh WebAppService	getSafeEffectList	/v1/faultService/getSafeEffectList
./add.sh WebAppService	getSecondTypeTicketList	/v1/faultService/getSecondTypeTicketList
./add.sh WebAppService	getSecondTypeTicketListForTicketDetail	/v1/faultService/getSecondTypeTicketListForTicketDetail
./add.sh WebAppService	getSelfReportPoint	/v1/reportService/getSelfReportPoint
./add.sh WebAppService	getSparePartsDetail	/v1/otherService/getSparePartsDetail
./add.sh WebAppService	getStatementList	/v1/reportService/getStatementList
./add.sh WebAppService	getStoreByStationId	/v1/otherService/getStoreByStationId
./add.sh WebAppService	getSysUserList	/v1/userService/getSysUserList
./add.sh WebAppService	getTableList	/v1/devService/getTableList
./add.sh WebAppService	getUserList	/v1/userService/getUserList
./add.sh WebAppService	getWeather	/v1/powerStationService/getWeather
./add.sh WebAppService	getWorkTicketList	/v1/faultService/getWorkTicketList
./add.sh WebAppService	getWorkTicketListForTicketDetail	/v1/faultService/getWorkTicketListForTicketDetail
./add.sh WebAppService	getWorkTicketRunningCount	/v1/faultService/getWorkTicketRunningCount
./add.sh WebAppService	getWorkTicketUserList	/v1/faultService/getWorkTicketUserList
./add.sh WebAppService	getinverterType	/v1/devService/getinverterType
./add.sh WebAppService	getreportPermissionByUser	/v1/reportService/getPsIdByUserId
./add.sh WebAppService	handleValue	/v1/reportService/handleValue
./add.sh WebAppService	modifyDeviceInfo	/v1/devService/modifyDeviceInfo
./add.sh WebAppService	operaStoreSpareParts	/v1/otherService/operaStoreSpareParts
./add.sh WebAppService	operateBillTransferToUser	/v1/faultService/operateBillTransferToUser
./add.sh WebAppService	queryAllStockInventory	/v1/otherService/queryAllStockInventory
./add.sh WebAppService	queryBatteryBoardsList	/v1/devService/queryBatteryBoardsList
./add.sh WebAppService	queryBatteryBoardsPointsData	/v1/devService/queryBatteryBoardsPointsData
./add.sh WebAppService	queryCodeByType	/v1/commonService/queryCodeByType
./add.sh WebAppService	queryDeviceInfoList	/v1/devService/queryDeviceInfoList
./add.sh WebAppService	queryElectricityCalendarData	/v1/reportService/queryElectricityCalendarData
./add.sh WebAppService	queryFaultCodes	/v1/faultService/queryFaultCodes
./add.sh WebAppService	queryFaultLevelAndType	/v1/faultService/queryFaultLevelAndType
./add.sh WebAppService	queryFaultNames	/v1/faultService/queryFaultNames
./add.sh WebAppService	queryMaterialType	/v1/otherService/queryMaterialType
./add.sh WebAppService	queryNounAndKlgList	/v1/faultService/queryNounAndKlgList
./add.sh WebAppService	queryNounList	/v1/faultService/queryNounList
./add.sh WebAppService	queryOptTickctInfo	/v1/faultService/queryOptTickctInfo
./add.sh WebAppService	queryOrgIdByUser	/v1/userService/queryOrgIdByUser
./add.sh WebAppService	queryPsCountryList	/v1/commonService/queryPsCountryList
./add.sh WebAppService	queryPsProvcnList	/v1/commonService/queryPsProvcnList
./add.sh WebAppService	queryPsTypeByPsId	/v1/powerStationService/queryPsTypeByPsId
./add.sh WebAppService	querySparePartsList	/v1/otherService/querySparePartsList
./add.sh WebAppService	queryStoreList	/v1/otherService/queryStoreList
./add.sh WebAppService	querySysTimezone	/v1/commonService/querySysTimezone
./add.sh WebAppService	queryUnInventorySpareList	/v1/otherService/queryUnInventorySpareList
./add.sh WebAppService	renewOperation	/v1/devService/renewOperation
./add.sh WebAppService	saveCustomReport	/v1/reportService/saveCustomReport
./add.sh WebAppService	saveDutyInfo	/v1/otherService/saveDutyInfo
./add.sh WebAppService	saveInventory	/v1/otherService/saveInventory
./add.sh WebAppService	saveMaterial	/v1/devService/saveMaterial
./add.sh WebAppService	saveSecondTypeTicket	/v1/faultService/saveSecondTypeTicket
./add.sh WebAppService	saveSelfReportPoint	/v1/reportService/saveSelfReportPoint
./add.sh WebAppService	saveWorkTicket	/v1/faultService/saveWorkTicket
./add.sh WebAppService	secondTypeTicketFlowImplementStep	/v1/faultService/secondTypeTicketFlowImplementStep
./add.sh WebAppService	secondTypeTicketFlowTransferStep	/v1/faultService/secondTypeTicketFlowTransferStep
./add.sh WebAppService	secondTypeUpdateSign	/v1/faultService/secondTypeUpdateSign
./add.sh WebAppService	selectPowerPageList	/v1/powerStationService/selectPowerPageList
./add.sh WebAppService	showAnalyzefxDetail	/v1/reportService/showAnalyzefxDetail
./add.sh WebAppService	showFxReport	/v1/reportService/showFxReport
./add.sh WebAppService	showMaterNameList	/v1/otherService/showMaterNameList
./add.sh WebAppService	showMaterSubTypeList	/v1/otherService/showMaterSubTypeList
./add.sh WebAppService	showTjReport	/v1/reportService/showTjReport
./add.sh WebAppService	templateLikesInfo	/v1/faultService/templateLikesInfo
./add.sh WebAppService	updOptTicketInfo	/v1/faultService/updOptTicketInfo
./add.sh WebAppService	updataWorkTicketAfterStartProcess	/v1/faultService/updataWorkTicketAfterStartProcess
./add.sh WebAppService	updateBillTicketForTask	/v1/faultService/updateBillTicketForTask
./add.sh WebAppService	updateDutyInfo	/v1/otherService/updateDutyInfo
./add.sh WebAppService	updateKnowledgeBaseUseNumber	/v1/faultService/updateKnowledgeBaseUseNumber
./add.sh WebAppService	updateMaterial	/v1/otherService/updateMaterial
./add.sh WebAppService	updateSpareParts	/v1/otherService/updateSpareParts
./add.sh WebAppService	updateStopReason	/v1/devService/updateStopReason
./add.sh WebAppService	updateTemplate	/v1/faultService/updateKnowledgeBaseCitationCount
