#!/bin/bash

echo "################################################################################"
echo "# $1"
awk '!/^\t"/{print;next} !visited[$0]++{print}' $1 > /tmp/z
diff $1 /tmp/z
cp /tmp/z $1

