package AppService

import (
	"GoSungro/iSolarCloud/AppService/getPowerDevicePointNames"
	"GoSungro/iSolarCloud/api"
	"fmt"
	"reflect"
	"strings"
)


var endpoints = [][]string {
	{"AppService","acceptPsSharing","/v1/powerStationService/acceptPsSharing"},
	{"AppService","activateEmail","/v1/userService/activateEmail"},
	{"AppService","addConfig","/devDataHandleService/addConfig"},
	{"AppService","addDeviceRepair","/v1/devService/addDeviceRepair"},
	{"AppService","addDeviceToStructureForHousehold","/devDataHandleService/addDeviceToStructureForHousehold"},
	{"AppService","addDeviceToStructureForHouseholdByPsIdS","/devDataHandleService/addDeviceToStructureForHouseholdByPsIdS"},
	{"AppService","addFault","/v1/faultService/addFault"},
	{"AppService","addFaultOrder","/v1/faultService/addFaultOrder"},
	{"AppService","addFaultPlan","/v1/faultService/addFaultPlan"},
	{"AppService","addFaultRepairSteps","/v1/faultService/addFaultRepairSteps"},
	{"AppService","addHouseholdEvaluation","/v1/faultService/addHouseholdEvaluation"},
	{"AppService","addHouseholdLeaveMessage","/v1/faultService/addHouseholdLeaveMessage"},
	{"AppService","addHouseholdOpinionFeedback","/v1/faultService/addHouseholdOpinionFeedback"},
	{"AppService","addHouseholdWorkOrder","/v1/faultService/addHouseholdWorkOrder"},
	{"AppService","addOnDutyInfo","/v1/otherService/addOnDutyInfo"},
	{"AppService","addOperRule","/v1/faultService/addOperRule"},
	{"AppService","addOrDelPsStructure","/v1/devService/addOrDelPsStructure"},
	{"AppService","addOrderStep","/v1/faultService/addOrderStep"},
	{"AppService","addPowerStationForHousehold","/v1/powerStationService/addPowerStationForHousehold"},
	{"AppService","addPowerStationInfo","/v1/powerStationService/addPowerStationInfo"},
	{"AppService","addReportConfigEmail","/v1/reportService/addReportConfigEmail"},
	{"AppService","addSysAdvancedParam","/v1/devService/addSysAdvancedParam"},
	{"AppService","addSysOrgNew","/v1/otherService/addSysOrgNew"},
	{"AppService","aliPayAppTest","/onlinepay/aliPayAppTest"},
	{"AppService","auditOperRule","/v1/faultService/auditOperRule"},
	{"AppService","batchAddStationBySn","/v1/powerStationService/batchAddStationBySn"},
	{"AppService","batchImportSN","/v1/devService/batchImportSN"},
	{"AppService","batchInsertUserAndOrg","/v1/userService/batchInsertUserAndOrg"},
	{"AppService","batchModifyDevicesInfoAndPropertis","/v1/devService/batchModifyDevicesInfoAndPropertis"},
	{"AppService","batchProcessPlantReport","/v1/powerStationService/batchProcessPlantReport"},
	{"AppService","batchUpdateDeviceSim","/v1/devService/batchUpdateDeviceSim"},
	{"AppService","batchUpdateUserIsAgreeGdpr","/v1/userService/batchUpdateUserIsAgreeGdpr"},
	{"AppService","boundMobilePhone","/v1/userService/boundMobilePhone"},
	{"AppService","boundUserMail","/v1/userService/boundUserMail"},
	{"AppService","caculateDeviceInputDiscrete","/v1/devService/caculateDeviceInputDiscrete"},
	{"AppService","calculateDeviceDiscrete","/v1/devService/calculateDeviceDiscrete"},
	{"AppService","calculateInitialCompensationData","/v1/powerStationService/calculateInitialCompensationData"},
	{"AppService","cancelDeliverMail","/v1/messageService/cancelDeliverMail"},
	{"AppService","cancelOrderScan","/v1/devService/cancelOrderScan"},
	{"AppService","cancelParamSetTask","/v1/devService/cancelParamSetTask"},
	{"AppService","cancelPsSharing","/v1/powerStationService/cancelPsSharing"},
	{"AppService","cancelRechargeOrder","/onlinepay/cancelRechargeOrder"},
	{"AppService","changRechargeOrderToCancel","/onlinepay/changRechargeOrderToCancel"},
	{"AppService","changeHouseholdUser2Installer","/v1/orgService/changeHouseholdUser2Installer"},
	{"AppService","changeRemoteParam","/v1/devService/changeRemoteParam"},
	{"AppService","checkDealerOrgCode","/v1/orgService/checkDealerOrgCode"},
	{"AppService","checkDevSnIsBelongsToUser","/v1/userService/checkDevSnIsBelongsToUser"},
	{"AppService","checkInverterResult","/v1/devService/checkInverterResult"},
	{"AppService","checkIsCanDoParamSet","/v1/devService/checkIsCanDoParamSet"},
	{"AppService","checkIsIvScan","/v1/devService/checkIsIvScan"},
	{"AppService","checkOssObjectExist","/v1/commonService/checkOssObjectExist"},
	{"AppService","checkServiceIsConnect","/v1/commonService/checkServiceIsConnect"},
	{"AppService","checkTechnicalParameters","/v1/devService/checkTechnicalParameters"},
	{"AppService","checkUnitStatus","/v1/devService/checkUnitStatus"},
	{"AppService","checkUpRechargeDevicePaying","/onlinepay/checkUpRechargeDevicePaying"},
	{"AppService","checkUserAccountUnique","/v1/userService/checkUserAccountUnique"},
	{"AppService","checkUserAccountUniqueAll","/v1/userService/checkUserAccountUniqueAll"},
	{"AppService","checkUserInfoUnique","/v1/userService/checkUserInfoUnique"},
	{"AppService","checkUserIsExist","/v1/userService/checkUserIsExist"},
	{"AppService","checkUserListIsExist","/v1/userService/checkUserListIsExist"},
	{"AppService","checkUserPassword","/v1/userService/checkUserPassword"},
	{"AppService","cloudDeploymentRecord","/v1/commonService/cloudDeploymentRecord"},
	{"AppService","comfirmParamModel","/v1/devService/comfirmParamModel"},
	{"AppService","communicationModuleDetail","/v1/devService/communicationModuleDetail"},
	{"AppService","compareValidateCode","/v1/userService/compareValidateCode"},
	{"AppService","componentInfo2Cloud","/v1/devService/componentInfo2Cloud"},
	{"AppService","confirmFault","/v1/faultService/confirmFault"},
	{"AppService","confirmIvFault","/v1/devService/confirmIvFault"},
	{"AppService","confirmReportConfig","/v1/reportService/confirmReportConfig"},
	{"AppService","createAppkeyInfo","/v1/userService/createAppkeyInfo"},
	{"AppService","createRenewInvoice","/onlinepay/createRenewInvoice"},
	{"AppService","dealCommandReply","/devDataHandleService/dealCommandReply"},
	{"AppService","dealDeletePsFailPsDelete","/v1/powerStationService/dealDeletePsFailPsDelete"},
	{"AppService","dealFailRemoteUpgradeSubTasks","/v1/devService/dealFailRemoteUpgradeSubTasks"},
	{"AppService","dealFailRemoteUpgradeTasks","/v1/devService/dealFailRemoteUpgradeTasks"},
	{"AppService","dealFaultOrder","/v1/faultService/dealFaultOrder"},
	{"AppService","dealGroupStringDisableOrEnable","/v1/devService/dealGroupStringDisableOrEnable"},
	{"AppService","dealNumberOfServiceCalls2Mysql","/v1/commonService/dealNumberOfServiceCalls2Mysql"},
	{"AppService","dealParamSettingAfterComplete","/v1/devService/dealParamSettingAfterComplete"},
	{"AppService","dealPsDataSupplement","/v1/powerStationService/dealPsDataSupplement"},
	{"AppService","dealPsReportEmailSend","/v1/reportService/dealPsReportEmailSend"},
	{"AppService","dealRemoteUpgrade","/v1/devService/dealRemoteUpgrade"},
	{"AppService","dealSnElectrifyCheck","/v1/devService/dealSnElectrifyCheck"},
	{"AppService","dealSysDeviceSimFlowInfo","/v1/devService/dealSysDeviceSimFlowInfo"},
	{"AppService","dealSysDeviceSimInfo","/v1/devService/dealSysDeviceSimInfo"},
	{"AppService","definiteTimeDealSnExpRemind","/v1/devService/definiteTimeDealSnExpRemind"},
	{"AppService","definiteTimeDealSnStatus","/v1/devService/definiteTimeDealSnStatus"},
	{"AppService","delDeviceRepair","/v1/devService/delDeviceRepair"},
	{"AppService","delOperRule","/v1/faultService/delOperRule"},
	{"AppService","delayCallApiResidueTimes","/v1/commonService/delayCallApiResidueTimes"},
	{"AppService","deleteComponent","/v1/devService/deleteComponent"},
	{"AppService","deleteCustomerEmployee","/v1/devService/deleteCustomerEmployee"},
	{"AppService","deleteDeviceAccount","/v1/devService/deleteDeviceAccount"},
	{"AppService","deleteDeviceSimById","/v1/devService/deleteDeviceSimById"},
	{"AppService","deleteElectricitySettlementData","/v1/otherService/deleteElectricitySettlementData"},
	{"AppService","deleteFaultPlan","/v1/faultService/deleteFaultPlan"},
	{"AppService","deleteFirmwareFiles","/v1/commonService/deleteFirmwareFiles"},
	{"AppService","deleteHouseholdEvaluation","/v1/faultService/deleteHouseholdEvaluation"},
	{"AppService","deleteHouseholdLeaveMessage","/v1/faultService/deleteHouseholdLeaveMessage"},
	{"AppService","deleteHouseholdWorkOrder","/v1/faultService/deleteHouseholdWorkOrder"},
	{"AppService","deleteInverterSnInChnnl","/devDataHandleService/deleteInverterSnInChnnl"},
	{"AppService","deleteModuleLog","/integrationService/deleteModuleLog"},
	{"AppService","deleteOnDutyInfo","/v1/otherService/deleteOnDutyInfo"},
	{"AppService","deleteOperateBillFile","/v1/faultService/deleteOperateBillFile"},
	{"AppService","deleteOssObject","/v1/commonService/deleteOssObject"},
	{"AppService","deletePowerDevicePointById","/v1/reportService/deletePowerDevicePointById"},
	{"AppService","deletePowerPicture","/v1/powerStationService/deletePowerPicture"},
	{"AppService","deletePowerRobotInfoBySnAndPsId","/v1/devService/deletePowerRobotInfoBySnAndPsId"},
	{"AppService","deletePowerRobotSweepStrategy","/v1/devService/deletePowerRobotSweepStrategy"},
	{"AppService","deleteProductionData","/v1/devService/deleteProductionData"},
	{"AppService","deletePs","/v1/powerStationService/deletePs"},
	{"AppService","deleteRechargeOrder","/onlinepay/deleteRechargeOrder"},
	{"AppService","deleteRegularlyConnectionInfo","/v1/commonService/deleteRegularlyConnectionInfo"},
	{"AppService","deleteReportConfigEmailAddr","/v1/reportService/deleteReportConfigEmailAddr"},
	{"AppService","deleteSysAdvancedParam","/v1/devService/deleteSysAdvancedParam"},
	{"AppService","deleteSysOrgNew","/v1/otherService/deleteSysOrgNew"},
	{"AppService","deleteTemplate","/v1/devService/deleteTemplate"},
	{"AppService","deleteUserInfoAllByUserId","/v1/userService/deleteUserInfoAllByUserId"},
	{"AppService","deviceInputDiscreteDeleteTime","/v1/devService/deviceInputDiscreteDeleteTime"},
	{"AppService","deviceInputDiscreteGetTime","/v1/devService/deviceInputDiscreteGetTime"},
	{"AppService","deviceInputDiscreteInsertTime","/v1/devService/deviceInputDiscreteInsertTime"},
	{"AppService","deviceInputDiscreteUpdateTime","/v1/devService/deviceInputDiscreteUpdateTime"},
	{"AppService","devicePointsDataFromMySql","/v1/devService/devicePointsDataFromMySql"},
	{"AppService","deviceReplace","/v1/devService/deviceReplace"},
	{"AppService","editDeviceRepair","/v1/devService/editDeviceRepair"},
	{"AppService","editOperRule","/v1/faultService/editOperRule"},
	{"AppService","energyPovertyAlleviation","/v1/orgService/energyPovertyAlleviation"},
	{"AppService","energyTrend","/v1/powerStationService/energyTrend"},
	{"AppService","exportParamSettingValPDF","/v1/devService/exportParamSettingValPDF"},
	{"AppService","exportPlantReportPDF","/v1/powerStationService/exportPlantReportPDF"},
	{"AppService","faultAutoClose","/v1/faultService/faultAutoClose"},
	{"AppService","faultCloseRemindOrderHandler","/v1/faultService/faultCloseRemindOrderHandler"},
	{"AppService","findCodeValueList","/v1/commonService/findCodeValueList"},
	{"AppService","findEmgOrgInfo","/v1/otherService/findEmgOrgInfo"},
	{"AppService","findEnvironmentInfo","/v1/devService/findEnvironmentInfo"},
	{"AppService","findFromHbaseAndRedis","/v1/commonService/findFromHbaseAndRedis"},
	{"AppService","findInfoByuuid","/v1/devService/findInfoByuuid"},
	{"AppService","findLossAnalysisList","/v1/powerStationService/findLossAnalysisList"},
	{"AppService","findOnDutyInfo","/v1/otherService/findOnDutyInfo"},
	{"AppService","findPsType","/v1/powerStationService/findPsType"},
	{"AppService","findSingleStationPR","/v1/powerStationService/findSingleStationPR"},
	{"AppService","findUserPassword","/v1/devService/findUserPassword"},
	{"AppService","genTLSUserSigByUserAccount","/v1/userService/genTLSUserSigByUserAccount"},
	{"AppService","generateRandomPassword","/v1/userService/generateRandomPassword"},
	{"AppService","getAPIServiceInfo","/v1/commonService/getAPIServiceInfo"},
	{"AppService","getAccessedPermission","/v1/commonService/getAccessedPermission"},
	{"AppService","getAllDeviceByPsId","/v1/devService/getAllDeviceByPsId"},
	{"AppService","getAllPowerDeviceSetName","/v1/devService/getAllPowerDeviceSetName"},
	{"AppService","getAllPowerRobotViewInfoByPsId","/v1/devService/getAllPowerRobotViewInfoByPsId"},
	{"AppService","getAllPsIdByOrgIds","/v1/devService/getAllPsIdByOrgIds"},
	{"AppService","getAllUserRemindCount","/v1/devService/getAllUserRemindCount"},
	{"AppService","getAndOutletsAndUnit","/v1/devService/getAndOutletsAndUnit"},
	{"AppService","getApiCallsForAppkeys","/v1/commonService/getApiCallsForAppkeys"},
	{"AppService","getAreaInfoCodeByCounty","/v1/commonService/getAreaInfoCodeByCounty"},
	{"AppService","getAreaList","/v1/powerStationService/getAreaList"},
	{"AppService","getAutoCreatePowerStation","/v1/powerStationService/getAutoCreatePowerStation"},
	{"AppService","getBackReadValue","/v1/devService/getBackReadValue"},
	{"AppService","getBatchNewestPointData","/v1/devService/getBatchNewestPointData"},
	{"AppService","getCallApiResidueTimes","/v1/commonService/getCallApiResidueTimes"},
	{"AppService","getChangedPsListByTime","/v1/powerStationService/getChangedPsListByTime"},
	{"AppService","getChnnlListByPsId","/v1/devService/getChnnlListByPsId"},
	{"AppService","getCloudList","/v1/commonService/getCloudList"},
	{"AppService","getCloudServiceMappingConfig","/v1/commonService/getCloudServiceMappingConfig"},
	{"AppService","getCommunicationDeviceConfigInfo","/v1/devService/getCommunicationDeviceConfigInfo"},
	{"AppService","getCommunicationModuleMonitorData","/v1/devService/getCommunicationModuleMonitorData"},
	{"AppService","getComponentModelFactory","/v1/devService/getComponentModelFactory"},
	{"AppService","getConfigList","/devDataHandleService/getConfigList"},
	{"AppService","getConnectionInfoBySnAndLocalPort","/v1/commonService/getConnectionInfoBySnAndLocalPort"},
	{"AppService","getCountDown","/v1/devService/getCountDown"},
	{"AppService","getCountryServiceInfo","/v1/commonService/getCountryServiceInfo"},
	{"AppService","getCounty","/v1/commonService/getCounty"},
	{"AppService","getCustomerEmployee","/v1/devService/getCustomerEmployee"},
	{"AppService","getCustomerList","/v1/devService/getCustomerList"},
	{"AppService","getDataFromHBase","/v1/commonService/getDataFromHBase"},
	{"AppService","getDataFromHbaseByRowKey","/v1/commonService/getDataFromHbaseByRowKey"},
	{"AppService","getDevInstalledPowerByPsId","/v1/devService/getDevInstalledPowerByPsId"},
	{"AppService","getDevRecord","/v1/devService/getDevRecord"},
	{"AppService","getDevRunRecordList","/v1/devService/getDevRunRecordList"},
	{"AppService","getDevSimByList","/v1/devService/getDevSimByList"},
	{"AppService","getDevSimList","/v1/devService/getDevSimList"},
	{"AppService","getDeviceAccountById","/v1/devService/getDeviceAccountById"},
	{"AppService","getDeviceFaultStatisticsData","/v1/devService/getDeviceFaultStatisticsData"},
	{"AppService","getDeviceInfo","/v1/devService/getDeviceInfo"},
	{"AppService","getDeviceList","/v1/devService/getDeviceList"},
	{"AppService","getDeviceModelInfoList","/v1/devService/getDeviceModelInfoList"},
	{"AppService","getDevicePointMinuteDataList","/v1/commonService/getDevicePointMinuteDataList"},
	{"AppService","getDevicePoints","/v1/devService/getDevicePoints"},
	{"AppService","getDevicePropertys","/v1/devService/getDevicePropertys"},
	{"AppService","getDeviceRepairDetail","/v1/devService/getDeviceRepairDetail"},
	{"AppService","getDeviceTechBranchCount","/v1/devService/getDeviceTechBranchCount"},
	{"AppService","getDeviceTypeInfoList","/v1/devService/getDeviceTypeInfoList"},
	{"AppService","getDeviceTypeList","/v1/devService/getDeviceTypeList"},
	{"AppService","getDstInfo","/v1/userService/getDstInfo"},
	{"AppService","getElectricitySettlementData","/v1/otherService/getElectricitySettlementData"},
	{"AppService","getElectricitySettlementDetailData","/v1/otherService/getElectricitySettlementDetailData"},
	{"AppService","getEncryptPublicKey","/v1/commonService/getEncryptPublicKey"},
	{"AppService","getFaultCount","/v1/faultService/getFaultCount"},
	{"AppService","getFaultDetail","/v1/faultService/getFaultDetail"},
	{"AppService","getFaultMsgByFaultCode","/v1/faultService/getFaultMsgByFaultCode"},
	{"AppService","getFaultMsgListByPageWithYYYYMM","/v1/faultService/getFaultMsgListByPageWithYYYYMM"},
	{"AppService","getFaultMsgListWithYYYYMM","/v1/faultService/getFaultMsgListWithYYYYMM"},
	{"AppService","getFaultPlanList","/v1/faultService/getFaultPlanList"},
	{"AppService","getFileOperationRecordOne","/v1/commonService/getFileOperationRecordOne"},
	{"AppService","getFormulaFaultAnalyseList","/v1/powerStationService/getFormulaFaultAnalyseList"},
	{"AppService","getGroupStringCheckResult","/v1/devService/getGroupStringCheckResult"},
	{"AppService","getGroupStringCheckRule","/v1/devService/getGroupStringCheckRule"},
	{"AppService","getHisData","/v1/devService/getHisData"},
	{"AppService","getHistoryInfo","/v1/powerStationService/getHistoryInfo"},
	{"AppService","getHouseholdEvaluation","/v1/faultService/getHouseholdEvaluation"},
	{"AppService","getHouseholdLeaveMessage","/v1/faultService/getHouseholdLeaveMessage"},
	{"AppService","getHouseholdOpinionFeedback","/v1/faultService/getHouseholdOpinionFeedback"},
	{"AppService","getHouseholdPsInstallerByUserId","/v1/userService/getHouseholdPsInstallerByUserId"},
	{"AppService","getHouseholdStoragePsReport","/v1/powerStationService/getHouseholdStoragePsReport"},
	{"AppService","getHouseholdUserInfo","/v1/userService/getHouseholdUserInfo"},
	{"AppService","getHouseholdWorkOrderInfo","/v1/faultService/getHouseholdWorkOrderInfo"},
	{"AppService","getHouseholdWorkOrderList","/v1/faultService/getHouseholdWorkOrderList"},
	{"AppService","getI18nConfigByType","/integrationService/i18nfile/getI18nConfigByType"},
	{"AppService","getI18nFileInfo","/integrationService/i18nfile/getI18nFileInfo"},
	{"AppService","getI18nInfoByKey","/integrationService/i18nfile/getI18nInfoByKey"},
	{"AppService","getI18nVersion","/integrationService/international/getI18nVersion"},
	{"AppService","getIncomeSettingInfos","/v1/powerStationService/getIncomeSettingInfos"},
	{"AppService","getInfoFromAMap","/v1/commonService/getInfoFromAMap"},
	{"AppService","getInfomationFromRedis","/v1/devService/getInfomationFromRedis"},
	{"AppService","getInstallInfoList","/v1/orgService/getInstallInfoList"},
	{"AppService","getInstallerInfoByDealerOrgCodeOrId","/v1/orgService/getInstallerInfoByDealerOrgCodeOrId"},
	{"AppService","getInvertDataList","/v1/devService/getInvertDataList"},
	{"AppService","getInverterDataCount","/v1/devService/getInverterDataCount"},
	{"AppService","getInverterProcess","/v1/devService/getInverterProcess"},
	{"AppService","getInverterUuidBytotalId","/v1/devService/getInverterUuidBytotalId"},
	{"AppService","getIvEchartsData","/v1/devService/getIvEchartsData"},
	{"AppService","getIvEchartsDataById","/v1/devService/getIvEchartsDataById"},
	{"AppService","getKpiInfo","/v1/powerStationService/getKpiInfo"},
	{"AppService","getListMiFromHBase","/v1/commonService/getListMiFromHBase"},
	{"AppService","getMapInfo","/v1/powerStationService/getMapInfo"},
	{"AppService","getMapMiFromHBase","/v1/commonService/getMapMiFromHBase"},
	{"AppService","getMenuAndPrivileges","/v1/userService/getMenuAndPrivileges"},
	{"AppService","getMicrogridEStoragePsReport","/v1/powerStationService/getMicrogridEStoragePsReport"},
	{"AppService","getModuleLogInfo","/integrationService/getModuleLogInfo"},
	{"AppService","getModuleLogTaskList","/integrationService/getModuleLogTaskList"},
	{"AppService","getNationProvJSON","/v1/commonService/getNationProvJSON"},
	{"AppService","getNeedOpAsynOpRecordList","/v1/commonService/getNeedOpAsynOpRecordList"},
	{"AppService","getNoticeInfo","/v1/otherService/getNoticeInfo"},
	{"AppService","getNumberOfServiceCalls","/v1/commonService/getNumberOfServiceCalls"},
	{"AppService","getOSSConfig","/v1/commonService/getOSSConfig"},
	{"AppService","getOperRuleDetail","/v1/faultService/getOperRuleDetail"},
	{"AppService","getOperateBillFileId","/v1/faultService/getOperateBillFileId"},
	{"AppService","getOperateTicketForDetail","/v1/faultService/getOperateTicketForDetail"},
	{"AppService","getOrCreateNetEaseUserToken","/v1/userService/getOrCreateNetEaseUserToken"},
	{"AppService","getOrderDataList","/v1/faultService/getOrderDataList"},
	{"AppService","getOrderDataSql2","/v1/devService/getOrderDataSql2"},
	{"AppService","getOrderDatas","/v1/devService/getOrderDatas"},
	{"AppService","getOrderDetail","/v1/faultService/getOrderDetail"},
	{"AppService","getOrderStatistics","/v1/faultService/getOrderStatistics"},
	{"AppService","getOrgIdNameByUserId","/v1/orgService/getOrgIdNameByUserId"},
	{"AppService","getOrgInfoByDealerOrgCode","/v1/orgService/getOrgInfoByDealerOrgCode"},
	{"AppService","getOrgListByName","/v1/orgService/getOrgListByName"},
	{"AppService","getOrgListByUserId","/v1/userService/getOrgListByUserId"},
	{"AppService","getOrgListForUser","/v1/orgService/getOrgListForUser"},
	{"AppService","getOssObjectStream","/v1/commonService/getOssObjectStream"},
	{"AppService","getOwnerFaultConfigList","/v1/faultService/getOwnerFaultConfigList"},
	{"AppService","getPListinfoFromMysql","/v1/powerStationService/getPListinfoFromMysql"},
	{"AppService","getParamSetTemplate4NewProtocol","/v1/devService/getParamSetTemplate4NewProtocol"},
	{"AppService","getParamSetTemplatePointInfo","/v1/devService/getParamSetTemplatePointInfo"},
	{"AppService","getParamterSettingBase","/v1/devService/getParamterSettingBase"},
	{"AppService","getPhotoInfo","/v1/otherService/getPhotoInfo"},
	{"AppService","getPlanedOrNotPsList","/v1/faultService/getPlanedOrNotPsList"},
	{"AppService","getPlantReportPDFList","/v1/powerStationService/getPlantReportPDFList"},
	{"AppService","getPowerChargeSettingInfo","/v1/powerStationService/getPowerChargeSettingInfo"},
	{"AppService","getPowerDeviceModelTechList","/v1/devService/getPowerDeviceModelTechList"},
	{"AppService","getPowerDeviceModelTree","/v1/devService/getPowerDeviceModelTree"},
	{"AppService","getPowerDevicePointInfo","/v1/reportService/getPowerDevicePointInfo"},
	{"AppService","getPowerDevicePointNames","/v1/reportService/getPowerDevicePointNames"},
	{"AppService","getPowerDeviceSetTaskDetailList","/v1/devService/getPowerDeviceSetTaskDetailList"},
	{"AppService","getPowerDeviceSetTaskList","/v1/devService/getPowerDeviceSetTaskList"},
	{"AppService","getPowerFormulaFaultAnalyse","/v1/powerStationService/getPowerFormulaFaultAnalyse"},
	{"AppService","getPowerPictureList","/v1/powerStationService/getPowerPictureList"},
	{"AppService","getPowerRobotInfoByRobotSn","/v1/devService/getPowerRobotInfoByRobotSn"},
	{"AppService","getPowerRobotSweepAttrByPsId","/v1/devService/getPowerRobotSweepAttrByPsId"},
	{"AppService","getPowerRobotSweepStrategy","/v1/devService/getPowerRobotSweepStrategy"},
	{"AppService","getPowerRobotSweepStrategyList","/v1/devService/getPowerRobotSweepStrategyList"},
	{"AppService","getPowerSettingCharges","/v1/powerStationService/getPowerSettingCharges"},
	{"AppService","getPowerSettingHistoryRecords","/v1/powerStationService/getPowerSettingHistoryRecords"},
	{"AppService","getPowerStationBasicInfo","/v1/powerStationService/getPowerStationBasicInfo"},
	{"AppService","getPowerStationData","/v1/powerStationService/getPowerStationData"},
	{"AppService","getPowerStationForHousehold","/v1/powerStationService/getPowerStationForHousehold"},
	{"AppService","getPowerStationInfo","/v1/powerStationService/getPowerStationInfo"},
	{"AppService","getPowerStationPR","/v1/powerStationService/getPowerStationPR"},
	{"AppService","getPowerStationTableDataSql","/v1/devService/getPowerStationTableDataSql"},
	{"AppService","getPowerStationTableDataSqlCount","/v1/devService/getPowerStationTableDataSqlCount"},
	{"AppService","getPowerStatistics","/v1/powerStationService/getPowerStatistics"},
	{"AppService","getPowerTrendDayData","/v1/powerStationService/getPowerTrendDayData"},
	{"AppService","getPrivateCloudValidityPeriod","/v1/commonService/getPrivateCloudValidityPeriod"},
	{"AppService","getProvInfoListByNationCode","/v1/commonService/getProvInfoListByNationCode"},
	{"AppService","getPsAuthKey","/v1/powerStationService/getPsAuthKey"},
	{"AppService","getPsCurveInfo","/v1/devService/getPsCurveInfo"},
	{"AppService","getPsDataSupplementTaskList","/v1/powerStationService/getPsDataSupplementTaskList"},
	{"AppService","getPsDetail","/v1/powerStationService/getPsDetail"},
	{"AppService","getPsDetailByUserTokens","/v1/powerStationService/getPsDetailByUserTokens"},
	{"AppService","getPsDetailForSinglePage","/v1/powerStationService/getPsDetailForSinglePage"},
	{"AppService","getPsDetailWithPsType","/v1/powerStationService/getPsDetailWithPsType"},
	{"AppService","getPsHealthState","/v1/powerStationService/getPsHealthState"},
	{"AppService","getPsInstallerByPsId","/v1/orgService/getPsInstallerByPsId"},
	{"AppService","getPsInstallerOrgInfoByPsId","/v1/powerStationService/getPsInstallerOrgInfoByPsId"},
	{"AppService","getPsList","/v1/powerStationService/getPsList"},
	{"AppService","getPsListByName","/v1/powerStationService/getPsListByName"},
	{"AppService","getPsListForPsDataByPsId","/v1/powerStationService/getPsListForPsDataByPsId"},
	{"AppService","getPsListStaticData","/v1/powerStationService/getPsListStaticData"},
	{"AppService","getPsReport","/v1/reportService/getPsReport"},
	{"AppService","getPsUser","/v1/userService/getPsUser"},
	{"AppService","getPsWeatherList","/v1/powerStationService/getPsWeatherList"},
	{"AppService","getRechargeOrderDetail","/onlinepay/getRechargeOrderDetail"},
	{"AppService","getRechargeOrderItemDeviceList","/onlinepay/getRechargeOrderItemDeviceList"},
	{"AppService","getRechargeOrderList","/onlinepay/getRechargeOrderList"},
	{"AppService","getRegionalTree","/v1/orgService/getRegionalTree"},
	{"AppService","getRemoteParamSettingList","/v1/devService/getRemoteParamSettingList"},
	{"AppService","getRemoteUpgradeDeviceList","/v1/devService/getRemoteUpgradeDeviceList"},
	{"AppService","getRemoteUpgradeScheduleDetails","/v1/devService/getRemoteUpgradeScheduleDetails"},
	{"AppService","getRemoteUpgradeSubTasksList","/v1/devService/getRemoteUpgradeSubTasksList"},
	{"AppService","getRemoteUpgradeTaskList","/v1/devService/getRemoteUpgradeTaskList"},
	{"AppService","getReportData","/v1/powerStationService/getReportData"},
	{"AppService","getReportEmailConfigInfo","/v1/reportService/getReportEmailConfigInfo"},
	{"AppService","getReportExportColumns","/v1/reportService/getReportExportColumns"},
	{"AppService","getReportListByUserId","/v1/reportService/getReportListByUserId"},
	{"AppService","getRobotDynamicCleaningView","/v1/devService/getRobotDynamicCleaningView"},
	{"AppService","getRobotNumAndSweepCapacity","/v1/devService/getRobotNumAndSweepCapacity"},
	{"AppService","getRuleUnit","/v1/powerStationService/getRuleUnit"},
	{"AppService","getSendReportConfigCron","/v1/reportService/getSendReportConfigCron"},
	{"AppService","getSerialNum","/v1/devService/getSerialNum"},
	{"AppService","getShieldMapConditionList","/v1/commonService/getShieldMapConditionList"},
	{"AppService","getSimIdBySnList","/v1/devService/getSimIdBySnList"},
	{"AppService","getSingleIVData","/v1/devService/getSingleIVData"},
	{"AppService","getSnChangeRecord","/v1/devService/getSnChangeRecord"},
	{"AppService","getSnConnectionInfo","/v1/commonService/getSnConnectionInfo"},
	{"AppService","getStationInfoSql","/v1/devService/getStationInfoSql"},
	{"AppService","getSungwsConfigCache","/v1/commonService/getSungwsConfigCache"},
	{"AppService","getSungwsGlobalConfigCache","/v1/commonService/getSungwsGlobalConfigCache"},
	{"AppService","getSweepDevParamSetTemplate","/v1/devService/getSweepDevParamSetTemplate"},
	{"AppService","getSweepRobotDevList","/v1/devService/getSweepRobotDevList"},
	{"AppService","getSysMsg","/v1/otherService/getSysMsg"},
	{"AppService","getSysOrgNewList","/v1/otherService/getSysOrgNewList"},
	{"AppService","getSysOrgNewOne","/v1/otherService/getSysOrgNewOne"},
	{"AppService","getSysUserById","/v1/userService/getSysUserById"},
	{"AppService","getTableDataSql","/v1/devService/getTableDataSql"},
	{"AppService","getTableDataSqlCount","/v1/devService/getTableDataSqlCount"},
	{"AppService","getTemplateByInfoType","/v1/messageService/getTemplateByInfoType"},
	{"AppService","getTemplateList","/v1/devService/getTemplateList"},
	{"AppService","getUUIDByUpuuid","/v1/devService/getUUIDByUpuuid"},
	{"AppService","getUpTimePoint","/v1/devService/getUpTimePoint"},
	{"AppService","getUserById","/v1/userService/getUserById"},
	{"AppService","getUserByInstaller","/v1/userService/getUserByInstaller"},
	{"AppService","getUserDevOnlineOffineCount","/v1/devService/getUserDevOnlineOffineCount"},
	{"AppService","getUserGDPRAttrs","/v1/userService/getUserGDPRAttrs"},
	{"AppService","getUserHavePowerStationCount","/v1/userService/getUserHavePowerStationCount"},
	{"AppService","getUserInfoByUserAccounts","/v1/userService/getUserInfoByUserAccounts"},
	{"AppService","getUserList","/v1/userService/getUserList"},
	{"AppService","getUserPsOrderList","/v1/faultService/getUserPsOrderList"},
	{"AppService","getValFromHBase","/v1/commonService/getValFromHBase"},
	{"AppService","getValidateCode","/v1/userService/getValidateCode"},
	{"AppService","getValidateCodeAtRegister","/v1/userService/getValidateCodeAtRegister"},
	{"AppService","getWeatherInfo","/v1/powerStationService/getWeatherInfo"},
	{"AppService","getWechatPushConfig","/v1/userService/getWechatPushConfig"},
	{"AppService","getWorkInfo","/v1/otherService/getWorkInfo"},
	{"AppService","groupStringCheck","/v1/devService/groupStringCheck"},
	{"AppService","handleDevByCommunicationSN","/devDataHandleService/handleDevByCommunicationSN"},
	{"AppService","householdResetPassBySN","/v1/userService/householdResetPassBySN"},
	{"AppService","immediatePayment","/onlinepay/immediatePayment"},
	{"AppService","importExcelData","/v1/devService/importExcelData"},
	{"AppService","incomeStatistics","/v1/powerStationService/incomeStatistics"},
	{"AppService","informPush","/v1/messageService/informPush"},
	{"AppService","insertEmgOrgInfo","/v1/otherService/insertEmgOrgInfo"},
	{"AppService","insightSynDeviceStructure2Cloud","/v1/powerStationService/insightSynDeviceStructure2Cloud"},
	{"AppService","intoDataToHbase","/v1/commonService/intoDataToHbase"},
	{"AppService","ipLocationQuery","/v1/commonService/ipLocationQuery"},
	{"AppService","isHave2GSn","/v1/devService/isHave2GSn"},
	{"AppService","judgeDevIsHasInitSetTemplate","/v1/devService/judgeDevIsHasInitSetTemplate"},
	{"AppService","judgeIsSettingMan","/v1/faultService/judgeIsSettingMan"},
	{"AppService","listOssFiles","/v1/commonService/listOssFiles"},
	{"AppService","loadAreaInfo","/v1/commonService/loadAreaInfo"},
	{"AppService","loadPowerStation","/v1/powerStationService/loadPowerStation"},
	{"AppService","login","/v1/userService/login"},
	{"AppService","loginByToken","/v1/userService/loginByToken"},
	{"AppService","logout","/v1/userService/logout"},
	{"AppService","mobilePhoneHasBound","/v1/userService/mobilePhoneHasBound"},
	{"AppService","modifiedDeviceInfo","/v1/devService/modifiedDeviceInfo"},
	{"AppService","modifyEmgOrgStruc","/v1/otherService/modifyEmgOrgStruc"},
	{"AppService","modifyFaultPlan","/v1/faultService/modifyFaultPlan"},
	{"AppService","modifyOnDutyInfo","/v1/otherService/modifyOnDutyInfo"},
	{"AppService","modifyPassword","/v1/userService/modifyPassword"},
	{"AppService","modifyPersonalUnitList","/v1/userService/modifyPersonalUnitList"},
	{"AppService","modifyPsUser","/v1/userService/modifyPsUser"},
	{"AppService","moduleLogParamSet","/integrationService/moduleLogParamSet"},
	{"AppService","operateOssFile","/v1/commonService/operateOssFile"},
	{"AppService","operationPowerRobotSweepStrategy","/v1/devService/operationPowerRobotSweepStrategy"},
	{"AppService","orgPowerReport","/v1/orgService/orgPowerReport"},
	{"AppService","paramSetTryAgain","/v1/devService/paramSetTryAgain"},
	{"AppService","paramSetting","/v1/devService/paramSetting"},
	{"AppService","planPower","/v1/powerStationService/planPower"},
	{"AppService","powerDevicePointList","/v1/reportService/powerDevicePointList"},
	{"AppService","powerTrendChartData","/v1/powerStationService/powerTrendChartData"},
	{"AppService","psForcastInfo","/v1/powerStationService/psForcastInfo"},
	{"AppService","psHourPointsValue","/v1/powerStationService/psHourPointsValue"},
	{"AppService","queryAllPsIdAndName","/v1/powerStationService/queryAllPsIdAndName"},
	{"AppService","queryBatchCreatePsTaskList","/v1/powerStationService/queryBatchCreatePsTaskList"},
	{"AppService","queryBatchSpeedyAddPowerStationResult","/v1/powerStationService/queryBatchSpeedyAddPowerStationResult"},
	{"AppService","queryCardStatusCTCC","/v1/devService/queryCardStatusCTCC"},
	{"AppService","queryChildAccountList","/v1/userService/queryChildAccountList"},
	{"AppService","queryCompensationRecordData","/v1/powerStationService/queryCompensationRecordData"},
	{"AppService","queryCompensationRecordList","/v1/powerStationService/queryCompensationRecordList"},
	{"AppService","queryComponent","/v1/devService/queryComponent"},
	{"AppService","queryComponentTechnicalParam","/v1/devService/queryComponentTechnicalParam"},
	{"AppService","queryCountryGridAndRelation","/v1/devService/queryCountryGridAndRelation"},
	{"AppService","queryCountryList","/v1/commonService/queryCountryList"},
	{"AppService","queryCtrlTaskById","/v1/devService/queryCtrlTaskById"},
	{"AppService","queryDeviceInfo","/v1/devService/queryDeviceInfoForApp"},
	{"AppService","queryDeviceInfoForApp","/v1/devService/queryDeviceInfoForApp"},
	{"AppService","queryDeviceList","/v1/devService/queryDeviceList"},
	{"AppService","queryDeviceListByUserId","/v1/devService/queryDeviceListByUserId"},
	{"AppService","queryDeviceListForApp","/v1/devService/queryDeviceListForApp"},
	{"AppService","queryDeviceModelTechnical","/v1/devService/queryDeviceModelTechnical"},
	{"AppService","queryDevicePointDayMonthYearDataList","/v1/commonService/queryDevicePointDayMonthYearDataList"},
	{"AppService","queryDevicePointMinuteDataList","/v1/commonService/queryDevicePointMinuteDataList"},
	{"AppService","queryDevicePointsDayMonthYearDataList","/v1/commonService/queryDevicePointsDayMonthYearDataList"},
	{"AppService","queryDeviceRealTimeDataByPsKeys","/v1/devService/queryDeviceRealTimeDataByPsKeys"},
	{"AppService","queryDeviceRepairList","/v1/devService/queryDeviceRepairList"},
	{"AppService","queryDeviceTypeInfoList","/v1/devService/queryDeviceTypeInfoList"},
	{"AppService","queryEnvironmentList","/v1/devService/queryEnvironmentList"},
	{"AppService","queryFaultList","/v1/faultService/queryFaultList"},
	{"AppService","queryFaultPlanDetail","/v1/faultService/queryFaultPlanDetail"},
	{"AppService","queryFaultRepairSteps","/v1/faultService/queryFaultRepairSteps"},
	{"AppService","queryFaultTypeAndLevelByCode","/v1/faultService/queryFaultTypeAndLevelByCode"},
	{"AppService","queryFaultTypeByDevice","/v1/faultService/queryFaultTypeByDevice"},
	{"AppService","queryFaultTypeByDevicePage","/v1/faultService/queryFaultTypeByDevicePage"},
	{"AppService","queryFirmwareFilesPage","/v1/commonService/queryFirmwareFilesPage"},
	{"AppService","queryInfotoAlert","/v1/devService/queryInfotoAlert"},
	{"AppService","queryInverterModelList","/v1/devService/queryInverterModelList"},
	{"AppService","queryInverterVersionList","/v1/devService/queryInverterVersionList"},
	{"AppService","queryM2MCardInfoCMCC","/v1/devService/queryM2MCardInfoCMCC"},
	{"AppService","queryM2MCardTermInfoCMCC","/v1/devService/queryM2MCardTermInfoCMCC"},
	{"AppService","queryModelInfoByModelId","/v1/devService/queryModelInfoByModelId"},
	{"AppService","queryMutiPointDataList","/v1/commonService/queryMutiPointDataList"},
	{"AppService","queryNoticeList","/v1/otherService/queryNoticeList"},
	{"AppService","queryNumberOfRenewalReminders","/v1/devService/queryNumberOfRenewalReminders"},
	{"AppService","queryOperRules","/v1/faultService/queryOperRules"},
	{"AppService","queryOrderList","/v1/faultService/queryOrderList"},
	{"AppService","queryOrderStep","/v1/faultService/queryOrderStep"},
	{"AppService","queryOrgGenerationReport","/v1/orgService/queryOrgGenerationReport"},
	{"AppService","queryOrgInfoList","/v1/userService/queryOrgInfoList"},
	{"AppService","queryOrgPowerElecPercent","/v1/orgService/queryOrgPowerElecPercent"},
	{"AppService","queryOrgPsCompensationRecordList","/v1/powerStationService/queryOrgPsCompensationRecordList"},
	{"AppService","queryParamSettingTask","/v1/devService/queryParamSettingTask"},
	{"AppService","queryPersonalUnitList","/v1/userService/queryPersonalUnitList"},
	{"AppService","queryPointDataTopOne","/v1/devService/queryPointDataTopOne"},
	{"AppService","queryPowerStationInfo","/v1/powerStationService/queryPowerStationInfo"},
	{"AppService","queryPsAreaByUserIdAndAreaCode","/v1/powerStationService/queryPsAreaByUserIdAndAreaCode"},
	{"AppService","queryPsCompensationRecordList","/v1/powerStationService/queryPsCompensationRecordList"},
	{"AppService","queryPsDataByDate","/v1/powerStationService/queryPsDataByDate"},
	{"AppService","queryPsIdList","/v1/powerStationService/queryPsIdList"},
	{"AppService","queryPsListByUserIdAndAreaCode","/v1/powerStationService/queryPsListByUserIdAndAreaCode"},
	{"AppService","queryPsNameByPsId","/v1/devService/queryPsNameByPsId"},
	{"AppService","queryPsPrByDate","/v1/powerStationService/queryPsPrByDate"},
	{"AppService","queryPsProfit","/v1/powerStationService/queryPsProfit"},
	{"AppService","queryPsReportComparativeAnalysisOfPowerGeneration","/v1/powerStationService/queryPsReportComparativeAnalysisOfPowerGeneration"},
	{"AppService","queryPsStructureList","/v1/devService/queryPsStructureList"},
	{"AppService","queryPuuidsByCommandTotalId","/v1/devService/queryPuuidsByCommandTotalId"},
	{"AppService","queryPuuidsByCommandTotalId2","/v1/devService/queryPuuidsByCommandTotalId2"},
	{"AppService","queryRepairRuleList","/v1/devService/queryRepairRuleList"},
	{"AppService","queryReportListForManagementPage","/v1/reportService/queryReportListForManagementPage"},
	{"AppService","queryReportMsg","/v1/reportService/queryReportMsg"},
	{"AppService","querySharingPs","/v1/powerStationService/querySharingPs"},
	{"AppService","querySysAdvancedParam","/v1/devService/querySysAdvancedParam"},
	{"AppService","queryTimeBySN","/v1/devService/queryTimeBySN"},
	{"AppService","queryTrafficByDateCTCC","/v1/devService/queryTrafficByDateCTCC"},
	{"AppService","queryTrafficCTCC","/v1/devService/queryTrafficCTCC"},
	{"AppService","queryUnitList","/v1/userService/queryUnitList"},
	{"AppService","queryUnitUuidBytotalId","/v1/devService/queryUnitUuidBytotalId"},
	{"AppService","queryUserBtnPri","/v1/userService/queryUserBtnPri"},
	{"AppService","queryUserByUserIds","/v1/userService/queryUserByUserIds"},
	{"AppService","queryUserExtensionAttribute","/v1/userService/queryUserExtensionAttribute"},
	{"AppService","queryUserForStep","/v1/userService/queryUserForStep"},
	{"AppService","queryUserList","/v1/userService/queryUserList"},
	{"AppService","queryUserProcessPri","/v1/userService/queryUserProcessPri"},
	{"AppService","queryUserWechatBindRel","/v1/userService/queryUserWechatBindRel"},
	{"AppService","queryUuidByTotalIdAndUuid","/v1/devService/queryUuidByTotalIdAndUuid"},
	{"AppService","rechargeOrderSetMeal","/v1/devService/rechargeOrderSetMeal"},
	{"AppService","renewSendReportConfirmEmail","/v1/reportService/renewSendReportConfirmEmail"},
	{"AppService","reportList","/v1/powerStationService/reportList"},
	{"AppService","saveCustomerEmployee","/v1/devService/saveCustomerEmployee"},
	{"AppService","saveDevSimList","/v1/devService/saveDevSimList"},
	{"AppService","saveDeviceAccountBatchData","/v1/devService/saveDeviceAccountBatchData"},
	{"AppService","saveEnviromentIncomeInfos","/v1/powerStationService/saveEnviromentIncomeInfos"},
	{"AppService","saveEnvironmentCurve","/v1/devService/saveEnvironmentCurve"},
	{"AppService","saveFirmwareFile","/v1/commonService/saveFirmwareFile"},
	{"AppService","saveIncomeSettingInfos","/v1/powerStationService/saveIncomeSettingInfos"},
	{"AppService","saveOrUpdateGroupStringCheckRule","/v1/devService/saveOrUpdateGroupStringCheckRule"},
	{"AppService","saveParamModel","/v1/devService/saveParamModel"},
	{"AppService","savePowerCharges","/v1/powerStationService/savePowerCharges"},
	{"AppService","savePowerDevicePoint","/v1/reportService/savePowerDevicePoint"},
	{"AppService","savePowerRobotInfo","/v1/devService/savePowerRobotInfo"},
	{"AppService","savePowerRobotSweepAttr","/v1/devService/savePowerRobotSweepAttr"},
	{"AppService","savePowerSettingCharges","/v1/powerStationService/savePowerSettingCharges"},
	{"AppService","savePowerSettingInfo","/v1/powerStationService/savePowerSettingInfo"},
	{"AppService","saveProductionBatchData","/v1/devService/saveProductionBatchData"},
	{"AppService","saveRechargeOrderObj","/onlinepay/saveRechargeOrderObj"},
	{"AppService","saveRechargeOrderOtherInfo","/onlinepay/saveRechargeOrderOtherInfo"},
	{"AppService","saveRepair","/v1/faultService/saveRepair"},
	{"AppService","saveReportExportColumns","/v1/reportService/saveReportExportColumns"},
	{"AppService","saveSetParam","/v1/devService/saveSetParam"},
	{"AppService","saveSysUserMsg","/v1/otherService/saveSysUserMsg"},
	{"AppService","saveTemplate","/v1/devService/saveTemplate"},
	{"AppService","searchM2MMonthFlowCMCC","/v1/devService/searchM2MMonthFlowCMCC"},
	{"AppService","selectSysTranslationNames","/v1/reportService/selectSysTranslationNames"},
	{"AppService","sendPsTimeZoneInstruction","/devDataHandleService/sendPsTimeZoneInstruction"},
	{"AppService","setUpFormulaFaultAnalyse","/v1/powerStationService/setUpFormulaFaultAnalyse"},
	{"AppService","setUserGDPRAttrs","/v1/userService/setUserGDPRAttrs"},
	{"AppService","settingNotice","/v1/userService/settingNotice"},
	{"AppService","shareMyPs","/v1/powerStationService/shareMyPs"},
	{"AppService","sharePsBySN","/v1/powerStationService/sharePsBySN"},
	{"AppService","showInverterByUnit","/v1/devService/showInverterByUnit"},
	{"AppService","showOnlineUsers","/v1/userService/showOnlineUsers"},
	{"AppService","showWarning","/v1/userService/showWarning"},
	{"AppService","snIsExist","/v1/devService/snIsExist"},
	{"AppService","snsIsExist","/v1/devService/snsIsExist"},
	{"AppService","speedyAddPowerStation","/v1/powerStationService/speedyAddPowerStation"},
	{"AppService","stationDeviceHistoryDataList","/v1/powerStationService/stationDeviceHistoryDataList"},
	{"AppService","stationUnitsList","/v1/powerStationService/stationUnitsList"},
	{"AppService","stationsDiscreteData","/v1/devService/stationsDiscreteData"},
	{"AppService","stationsIncomeList","/v1/powerStationService/stationsIncomeList"},
	{"AppService","stationsPointReport","/v1/powerStationService/stationsPointReport"},
	{"AppService","stationsYearPlanReport","/v1/reportService/stationsYearPlanReport"},
	{"AppService","sureAndImportSelettlementData","/v1/otherService/sureAndImportSelettlementData"},
	{"AppService","sweepDevParamSet","/v1/devService/sweepDevParamSet"},
	{"AppService","sweepDevRunControl","/v1/devService/sweepDevRunControl"},
	{"AppService","sweepDevStrategyIssue","/v1/devService/sweepDevStrategyIssue"},
	{"AppService","sysTimeZoneList","/v1/commonService/sysTimeZoneList"},
	{"AppService","unLockUser","/v1/userService/unLockUser"},
	{"AppService","unlockChildAccount","/v1/userService/unlockChildAccount"},
	{"AppService","updateCommunicationModuleState","/v1/devService/updateCommunicationModuleState"},
	{"AppService","updateDevInstalledPower","/v1/devService/updateDevInstalledPower"},
	{"AppService","updateFault","/v1/faultService/updateFaultStatus"},
	{"AppService","updateFaultData","/v1/faultService/updateFaultData"},
	{"AppService","updateFaultMsgByFaultCode","/v1/faultService/updateFaultMsgByFaultCode"},
	{"AppService","updateFaultStatus","/v1/faultService/updateFaultStatus"},
	{"AppService","updateHouseholdWorkOrder","/v1/faultService/updateHouseholdWorkOrder"},
	{"AppService","updateInverterSn2ModuleSn","/devDataHandleService/updateInverterSn2ModuleSn"},
	{"AppService","updateOperateTicketAttachmentId","/v1/faultService/updateOperateTicketAttachmentId"},
	{"AppService","updateOrderDeviceByCustomerService","/onlinepay/updateOrderDeviceByCustomerService"},
	{"AppService","updateOwnerFaultConfig","/v1/faultService/updateOwnerFaultConfig"},
	{"AppService","updateParamSettingSysMsg","/v1/devService/updateParamSettingSysMsg"},
	{"AppService","updatePlatformLevelFaultLevel","/v1/faultService/updatePlatformLevelFaultLevel"},
	{"AppService","updatePowerDevicePoint","/v1/reportService/updatePowerDevicePoint"},
	{"AppService","updatePowerRobotInfo","/v1/devService/updatePowerRobotInfo"},
	{"AppService","updatePowerRobotSweepAttr","/v1/devService/updatePowerRobotSweepAttr"},
	{"AppService","updatePowerStationForHousehold","/v1/powerStationService/updatePowerStationForHousehold"},
	{"AppService","updatePowerStationInfo","/v1/powerStationService/updatePowerStationInfo"},
	{"AppService","updatePowerUserInfo","/v1/userService/updatePowerUserInfo"},
	{"AppService","updateReportConfigByEmailAddr","/v1/reportService/updateReportConfigByEmailAddr"},
	{"AppService","updateShareAttr","/v1/powerStationService/updateShareAttr"},
	{"AppService","updateSnIsSureFlag","/devDataHandleService/updateSnIsSureFlag"},
	{"AppService","updateStationPics","/v1/powerStationService/updateStationPics"},
	{"AppService","updateSysAdvancedParam","/v1/devService/updateSysAdvancedParam"},
	{"AppService","updateSysOrgNew","/v1/otherService/updateSysOrgNew"},
	{"AppService","updateTemplate","/v1/devService/updateDataCurveTemplate"},
	{"AppService","updateUinfoNetEaseUser","/v1/userService/updateUinfoNetEaseUser"},
	{"AppService","updateUserExtensionAttribute","/v1/userService/updateUserExtensionAttribute"},
	{"AppService","updateUserLanguage","/v1/userService/updateUserLanguage"},
	{"AppService","updateUserPosition","/v1/userService/updateUserPosition"},
	{"AppService","updateUserUpOrg","/v1/orgService/updateUserUpOrg"},
	{"AppService","upgrade","/v1/userService/upgrade"},
	{"AppService","upgrate","/v1/userService/upgrade"},
	{"AppService","uploadFileToOss","/v1/commonService/uploadFileToOss"},
	{"AppService","userAgreeGdprProtocol","/v1/userService/userAgreeGdprProtocol"},
	{"AppService","userInfoUniqueCheck","/v1/userService/userInfoUniqueCheck"},
	{"AppService","userMailHasBound","/v1/userService/userMailHasBound"},
	{"AppService","userRegister","/v1/userService/userRegister"},
}


type AreaStruct struct {
	Name api.AreaName
	EndPoints api.TypeEndPoints
}
var Area AreaStruct

func init() {
	ref := reflect.TypeOf(AreaStruct{})
	p := ref.String()
	s := ref.Name()
	Area.Name = api.AreaName(strings.TrimSuffix(p, "." + s))
	Area.EndPoints = api.CreateEndPoints(endpoints)

	for _, e := range Area.EndPoints {
		fmt.Printf("%s/%s -> %s\n",
			e.Area,
			e.Name,
			e.Url.String(),
			)

		if e.Name == "getPowerDevicePointNames" {
			fmt.Println("HEYHEYHEY")
			// foo := e.Resource.GetResource()
			// fmt.Printf("R:%v\n", foo)
			foo := getPowerDevicePointNames.Resource{}
			foo.Init()
			getPowerDevicePointNames.Init()
			(getPowerDevicePointNames.Resource)(e.Resource).Call()
			// e.Response = getPowerDevicePointNames.Resource{}
			// e.Request = getPowerDevicePointNames.Resource{}
			continue
		}

	}


	fmt.Println("HEY")
	foo := Area.EndPoints.GetEndPoint("getPowerDevicePointNames")
	foo.Resource = getPowerDevicePointNames.Resource{}
	// _ = foo.SetRequest(getPowerDevicePointNames.Request {
	// 	RequestCommon: api.RequestCommon {
	// 		Appkey:     "",
	// 		DeviceType: "",
	// 		Lang:       "",
	// 		SysCode:    "",
	// 		Token:      "",
	// 		UserID:     "",
	// 		ValidFlag:  "",
	// 	},
	// 	Extra:         "HOWDY",
	// })

	// foo.Resource = getPowerDevicePointNames.Resource {
	// 	Request:  getPowerDevicePointNames.Request {
	// 		RequestCommon: api.RequestCommon {
	// 			Get:        nil,
	// 			Set:        nil,
	// 			Appkey:     "",
	// 			DeviceType: "",
	// 			Lang:       "",
	// 			SysCode:    "",
	// 			Token:      "",
	// 			UserID:     "",
	// 			ValidFlag:  "",
	// 		},
	// 		Extra:         "",
	// 	},
	// 	Response: getPowerDevicePointNames.Response {
	// 		ResponseCommon: api.ResponseCommon {
	// 			Get:          nil,
	// 			Set:          nil,
	// 			ReqSerialNum: "",
	// 			ResultCode:   "",
	// 			ResultData:   nil,
	// 			ResultMsg:    "",
	// 		},
	// 		Another:        "",
	// 	},
	// }
	// foo.Resource.SetRequest(nil)
}


func PutMe(j api.Json)  {
	fmt.Println("Hello world!")
	fmt.Println(j)
}