// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package AppService

import "reflect"

var Types = map[string]reflect.Type{
	"AreaStruct": reflect.TypeOf((*AreaStruct)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"PutMe": reflect.ValueOf(PutMe),
}

var Variables = map[string]reflect.Value{
	"Area": reflect.ValueOf(&Area),
}

var Consts = map[string]reflect.Value{
}

